- type: job
  id: Chemist
  name: job-name-chemist
  description: job-description-chemist
  playTimeTracker: JobChemist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 28800 # DeltaV - 8 hours
  startingGear: ChemistGear
  icon: "JobIconChemist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Chemistry
  - Maintenance

- type: startingGear
  id: ChemistGear
  equipment:
    back: ClothingBackpackChemistryFilled
    shoes: ClothingShoesColorWhite
    id: ChemistryPDA
    ears: ClothingHeadsetMedical
    belt: ChemBag
    pocket1: HandLabeler
    # the purple glasses?
