- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  antagAdvantage: 5 # DeltaV - Reduced TC: External Access, JoL, Crew Monitor
  requirements:
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 2.5h
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - External # DeltaV
  - Paramedic # DeltaV - Add Paramedic access
  extendedAccess:
  - Chemistry
  # special: # DeltaV - role modifiers bad
  # - !type:AddComponentSpecial
  #  components:
  #  - type: SurgerySpeedModifier
  #    speedModifier: 1.75

- type: startingGear
  id: ParamedicGear
  equipment:
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalEMTFilled
  storage:
    back:
#    - EmergencyRollerBedSpawnFolded # DeltaV - move paramedic loadout to locker

- type: chameleonOutfit
  id: ParamedicChameleonOutfit
  job: Paramedic
  equipment:
    head: ClothingHeadHatParamedicsoft
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    neck: ClothingNeckStethoscope
    outerClothing: ClothingOuterCoatParamedicWB
    gloves: ClothingHandsGlovesLatex
