- type: job
  id: Paramedic
  name: job-name-paramedic
  description: job-description-paramedic
  playTimeTracker: JobParamedic
  requirements:
    - !type:RoleTimeRequirement
      role: JobMedicalDoctor
      time: 14400 #4 hrs
    - !type:OverallPlaytimeRequirement
      time: 54000 # 15 hrs
  startingGear: ParamedicGear
  icon: "JobIconParamedic"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Paramedic
  - Maintenance
  - External
  extendedAccess:
  - Chemistry

- type: startingGear
  id: ParamedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitParamedic
    back: ClothingBackpackParamedicFilled # DeltaV - Give Paramedics useful tools on spawn, see Resources/Prototypes/DeltaV/Catalog/Fills/Backpacks/StargerGear/backpack.yml
    shoes: ClothingShoesColorWhite
    id: ParamedicPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltParamedicFilled
    pocket1: HandheldGPSBasic # DeltaV - Give Paramedics useful tools on spawn
    pocket2: HandheldCrewMonitor # DeltaV - Give Paramedics useful tools on spawn
  innerclothingskirt: ClothingUniformJumpskirtParamedic
  satchel: ClothingBackpackSatchelParamedicFilled # DeltaV - Give Paramedics useful tools on spawn, see Resources/Prototypes/DeltaV/Catalog/Fills/Backpacks/StargerGear/satchel.yml
  duffelbag: ClothingBackpackDuffelParamedicFilled # DeltaV - Give Paramedics useful tools on spawn, see Resources/Prototypes/DeltaV/Catalog/Fills/Backpacks/StargerGear/duffelbag.yml
