# Delta-V - This file is licensed under AGPLv3
# Copyright (c) 2024 Delta-V Contributors
# See AGPLv3.txt for details.

- type: job
  id: MedicalBorg
  name: job-name-medical-borg
  description: job-description-medical-borg
  playTimeTracker: JobMedicalBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 216000 #60 hrs
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 21600 #6 hrs
  canBeAntag: false
  icon: JobIconMedicalBorg
  supervisors: job-supervisors-cmo
  jobEntity: PlayerBorgMedical
