## Static

- type: latheRecipePack
  id: ServiceStaticDeltaV
  recipes:
  - TrashBag
  - LightReplacer
  - Skimmer
  - RadioHandheld

- type: latheRecipePack
  id: ServiceBoardsStaticDeltaV
  recipes:
  - DeepFryerMachineCircuitboard

## Dynamic

- type: latheRecipePack
  id: Botany
  recipes:
  - PlantBagOfHolding
  - TrashBagOfHolding
  - PlantAnalyzer #Den plant analyzer

- type: latheRecipePack
  id: ServiceBoardsDeltaV
  recipes:
  - AdvancedMicrowaveMachineCircuitBoard
