## Static

- type: latheRecipePack
  id: ServiceStaticDeltaV
  recipes:
  - TrashBag
  - LightReplacer
  - Skimmer
  - RadioHandheld

- type: latheRecipePack
  id: ServiceBoardsStaticDeltaV
  recipes:
  - DeepFryerMachineCircuitboard

## Dynamic

- type: latheRecipePack
  id: Botany
  recipes:
  - PlantBagOfHolding
  - PlantAnalyzer # Port of Frontier Plant Analyzer
  - TrashBagOfHolding

- type: latheRecipePack
  id: ServiceBoardsDeltaV
  recipes:
  - AdvancedMicrowaveMachineCircuitBoard
