- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Epistemics # DeltaV
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 4h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 4h
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true # DeltaV
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  whitelisted: true # DeltaV
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
      - type: PsionicBonusChance # DeltaV - makes it more likely to become psionic.
        flatBonus: 0.025
      - type: Condemned # Goobstation - Nanotrasen owns your soul pal.
        soulOwnedNotDevil: true

- type: startingGear
  id: CaptainGear
  equipment:
    #shoes: ClothingShoesBootsLaceup # DeltaV - Commented out for loadout options
    eyes: ClothingEyesGlassesCommand
    #gloves: ClothingHandsGlovesCaptain # DeltaV - Commented out for loadout options
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter

- type: chameleonOutfit
  id: CaptainChameleonOutfit
  job: Captain
  hasMindShield: true
  equipment:
    head: ClothingHeadHatCapcap
    eyes: ClothingEyesGlassesCommand
    mask: ClothingMaskGasCaptain
    neck: ClothingNeckCloakCap
