- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # DeltaV - 10 hours
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Maintenance
  #- Service # Delta V: Access adjustments
  - Detective
  - Cryogenics # Delta V: Access adjustments
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
#    eyes: ClothingEyesGlassesSecurity # DeltaV
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
