- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 18000 #5 hrs
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  #- Brig # DeltaV - Removed brig access
  - Maintenance
  #- Service # DeltaV - Sec isn't service
  - Detective
  - Cryogenics
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
    #eyes: ClothingEyesGlassesSecurity # DeltaV - loadouts
    id: DetectivePDA
    gloves: ClothingHandsGlovesForensic # DeltaV - roundstart detective forensic gloves
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolster # DeltaV - loadouts
  storage:
    back:
    - Flash
    - ForensicPad
    - ForensicScanner

- type: chameleonOutfit
  id: DetectiveChameleonOutfit
  job: Detective
  hasMindShield: true
  equipment:
    head: ClothingHeadHatFedoraBrown
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckTieDet
    gloves: ClothingHandsGlovesForensic
