- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 3600 #1 hr
    - !type:RoleTimeRequirement
      role: JobDetective
      time: 3600 #1 hr, knowing how to use the tools is important
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hrs
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true # DeltaV
  supervisors: job-supervisors-captain
  canBeAntag: false
  whitelisted: true # DeltaV
  access:
  - HeadOfSecurity
  - Command
  #- Brig # DeltaV - Removed brig access
  - Security
  - Armory
  - Maintenance
  #- Service # DeltaV - Sec isn't service
  - External
  - Detective
  - Corpsman # DeltaV - added Corpsman access
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff
  - !type:ModifyPsionicChanceSpecial # DeltaV - Command Roles are more likely to be psionic.
    jobBonusChance: 0.05 # Additional 5% chance.

- type: startingGear
  id: HoSGear
  equipment:
    #eyes: ClothingEyesGlassesSecurity # DeltaV - loadouts
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    #pocket1: WeaponPistolMk58 # DeltaV - loadouts
  storage:
    back:
    - Flash
    #- MagazinePistol # DeltaV - loadouts

- type: chameleonOutfit
  id: HeadOfSecurityChameleonOutfit
  job: HeadOfSecurity
  hasMindShield: true
  equipment:
    mask: ClothingMaskGasSecurity
    neck: ClothingNeckCloakHos
