- type: job
  id: SecurityCadet
  name: job-name-cadet
  description: job-description-cadet
  playTimeTracker: JobSecurityCadet
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 21600 # DeltaV - 6 hours
#    - !type:DepartmentTimeRequirement # DeltaV - Removes time limit
#      department: Security
#      time: 54000 #15 hrs
#      inverted: true # stop playing intern if you're good at security!
  startingGear: SecurityCadetGear
  icon: "JobIconSecurityCadet"
  supervisors: job-supervisors-security
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Maintenance
  #- Service # Delta V: Access adjustments
  #- External # Delta V: Don't let cadets space themselves alone.
  #- Cryogenics # Delta V: Access adjustments
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityCadetGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitCadet # DeltaV - precious uniform budget has been allocated to real security uniforms for cadets. not good ones though.
#    shoes: ClothingShoesBootsCombatFilled # DeltaV
#    outerClothing: ClothingOuterArmorDuraVest # DeltaV
    id: SecurityCadetPDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
#    pocket1: WeaponPistolMk58Nonlethal # DeltaV - Security Cadet doesn't spawn with a gun
    pocket2: BookSecurity
