- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 1
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Maintenance
  #- Service # Delta V: Access adjustments
  - External
  #- Cryogenics # Delta V: Access adjustments
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SecurityOfficerGear
  equipment:
#    eyes: ClothingEyesGlassesSecurity # DeltaV
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58Nonlethal
