- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 18000 #5 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 #10 hrs
  weight: 5
  startingGear: WardenGear
  icon: "JobIconWarden"
  requireAdminNotify: true # DeltaV
  supervisors: job-supervisors-hos
  canBeAntag: false
  whitelisted: true # DeltaV
  access:
  - Security
  #- Brig # DeltaV - Removed brig access
  - Armory
  - Maintenance
  #- Service # DeltaV - Sec isn't service
  - External
  - Detective
  - Cryogenics
  - Corpsman # DeltaV - Warden requires access to the treatment of their prisoners.
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: WardenGear
  equipment:
    #eyes: ClothingEyesGlassesSecurity # DeltaV - loadouts
    id: WardenPDA
    ears: ClothingHeadsetSecurity
    #pocket1: WeaponPistolMk58Nonlethal # DeltaV - loadouts
  storage:
    back:
    - Flash
    #- MagazinePistol # DeltaV - loadouts

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
