- type: startingGear
  id: ElfGearMonkey
  equipment:
    head: ClothingHeadHatElf
    jumpsuit: ClothingUniformElf
#   shoes: ClothingShoesMiscElf #todo needs displacement and inventory template to wear shoes
  inhand:
  - SpearCandy
