- type: startingGear
  id: ElfGearMonkey
  equipment:
    head: ClothingHeadHatElf
    jumpsuit: ClothingUniformElf
#   shoes: ClothingShoesMiscElf #todo - needs proper displacement/inventory template
  inhand:
    - SpearCandy
