- type: antag
  id: Fugitive
  name: roles-antag-fugitive-name
  antagonist: true
  objective: roles-antag-fugitive-objective
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 1h

- type: startingGear
  id: FugitiveGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    ears: ClothingHeadsetGrey
    gloves: ClothingHandsGlovesColorYellow
    back: ClothingBackpackSatchel
    shoes: ClothingShoesChameleonNoSlips
    id: PassengerPDA
  #innerClothingSkirt: ClothingUniformJumpskirtPrisoner # FIXME doesnt work
  inhand:
  - ToolboxElectricalFilled
  storage:
    back:
    - FugitiveStash
