- type: antag
  id: MenaceSkeleton
  name: roles-antag-menace-skeleton-name
  objective: roles-antag-menace-skeleton-objective
  antagonist: true
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 48h

- type: startingGear
  id: MenaceSkeletonGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    ears: ClothingHeadsetGrey
    shoes: ClothingShoesChameleonNoSlips
