- type: antag
  id: Recruiter
  name: roles-antag-syndicate-recruiter-name
  objective: roles-antag-syndicate-recruiter-objective
  antagonist: false # you ask questions and write papers not kill people
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 24h
  - !type:RoleTimeRequirement
    role: JobLawyer
    time: 1h

- type: startingGear
  id: SyndicateRecruiterGear
  equipment:
    jumpsuit: ClothingUniformCybersunAttorney
    back: ClothingBackpackSatchel
    head: ClothingHeadHatFedoraBrown
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesColorWhite
    outerClothing: ClothingOuterCybersunOvercoat
    shoes: ClothingShoesLeather
    id: RecruiterPDA
    ears: ClothingHeadsetGreySyndicate
    pocket1: PenRecruiter
    pocket2: RubberStampSyndicate
    belt: ClothingBeltSyndicateUtility
  inhand:
    - RecruiterBriefcase
