- type: antag
  id: RoboNeuroticist
  name: roles-antag-roboneuroticist-name
  objective: roles-antag-roboneuroticist-objective
  antagonist: true # making evil borgs
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 48h
  - !type:RoleTimeRequirement
    role: JobRoboticist
    time: 2h

- type: startingGear
  id: RoboNeuroticistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitRoboNeuroticist
    back: ClothingBackpackSyndicate
    belt: ClothingBeltUtilityEngineering
    eyes: RoboNeuroticistVisor
    gloves: ClothingHandsGlovesRobohands
    shoes: ClothingShoesBootsMagSyndie
    outerClothing: ClothingOuterHardsuitRoboNeurotisist
    id: RoboNeuroticistPDA
    ears: ClothingHeadsetAltSyndicate
    pocket1: CyberPen
    pocket2: ThinTippedScrewdriver
    mask: ClothingMaskGasSyndicate
  storage:
    back:
    - RoboNeuroticistStash
    - Emag
    - EncryptionKeyBinary
    - NukeCoreContainer
    - SyndicateCircuitBoard
    - RoboNeuroticistPointer
