- type: antag
  id: SynthesisSpecialist
  name: roles-antag-syndicate-synthesis-name
  objective: roles-antag-syndicate-synthesis-objective
  antagonist: true # making poisions and shit on demand is evil
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 24h
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 2h

- type: startingGear
  id: SyndicateSynthesisGear
  equipment:
    jumpsuit: ClothingUniformInterdyneChemist
    back: ClothingBackpackChemistry
    belt: ChemBag
    eyes: ClothingEyesGlassesChemicalInterdyne
    gloves: ClothingHandsGlovesChemist
    outerClothing: ClothingOuterInterdyneChemistrySuit
    shoes: ClothingShoesEnclosedChem
    id: SyndiPDA
    ears: ClothingHeadsetAltSyndicateInterdyne # Gives them Traffic Coms (Todo: Add common coms upon ship & role rework)
    pocket1: HandLabeler
    pocket2: RubberStampSyndicate
    mask: ClothingMaskInterdyneChemistry
    head: ClothingHeadHatSyndie
  inhand:
    - DefibrillatorSyndicate
