- type: entity
  id: CrateServiceReplacementColoredLights
  name: Colored Lights Crate
  parent: CrateGenericSteel
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxColoredLighttube
        amount: 2

- type: entity
  id: CrateServiceReplacementMaintenanceLights
  name: Maintenance Lights Crate
  parent: CrateGenericSteel
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: BoxMaintenanceLightbulb
        amount: 2
