- type: job
  id: Clerk
  name: job-name-clerk
  description: job-description-clerk
  playTimeTracker: JobClerk
  antagAdvantage: 2 # DeltaV - Reduced TC: Security Radio and Access
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 10h
    - !type:RoleTimeRequirement
      role: JobLawyer
      time: 10h
    - !type:RoleTimeRequirement
      role: JobProsecutor
      time: 10h
  startingGear: ClerkGear
  icon: "JobIconClerk"
  requireAdminNotify: true
  supervisors: job-supervisors-cj
  canBeAntag: false
  access:
  - Justice
  - Clerk
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: ClerkGear
  equipment:
    #jumpsuit: ClothingUniformJumpsuitClerk
    #back: ClothingBackpackFilled
    #shoes: ClothingShoesBootsLaceup
    id: ClerkPDA
    ears: ClothingHeadsetJustice
    #innerClothingSkirt: ClothingUniformJumpskirtClerk
    #satchel: ClothingBackpackSatchelFilled
    #duffelbag: ClothingBackpackDuffelFilled
  storage:
    back:
    - BookSpaceLaw

- type: chameleonOutfit
  id: ClerkChameleonOutfit
  job: Clerk
  hasMindShield: true
  equipment:
      id: ClerkPDA
      ears: ClothingHeadsetJustice
      jumpsuit: ClothingUniformJumpsuitClerk
      neck: ClothingNeckTieBlack
      outerClothing: ClothingOuterClerkVest
