- type: job
  id: Roboticist
  name: job-name-roboticist
  description: job-description-roboticist
  playTimeTracker: JobRoboticist
  antagAdvantage: 4 # The shadow factory
  requirements:
  - !type:DepartmentTimeRequirement
    department: Epistemics
    time: 4h
  - !type:OverallPlaytimeRequirement
    time: 12h
  startingGear: RoboticistGear
  icon: JobIconRoboticist
  supervisors: job-supervisors-rd
  access:
  - Research
  - Robotics
  - Maintenance

- type: startingGear
  id: RoboticistGear
  equipment:
    ears: ClothingHeadsetRobotics

- type: chameleonOutfit
  id: RoboticistChameleonOutfit
  job: Roboticist
  equipment:
    id: RoboticistPDA
    ears: ClothingHeadsetRobotics
    head: ClothingOuterCardborg
    shoes: ClothingShoesBootsWinterRobo
