- type: job
  id: AtmosphericTechnician
  name: job-name-atmostech
  description: job-description-atmostech
  playTimeTracker: JobAtmosphericTechnician
  antagAdvantage: 4 # DeltaV - Reduced TC: External Access + Fireaxe + Free Hardsuit
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 36000 # DeltaV - 10 hours
  startingGear: AtmosphericTechnicianGear
  icon: "JobIconAtmosphericTechnician"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: AtmosphericTechnicianGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitAtmos
    back: ClothingBackpackAtmosphericsFilled
    shoes: ClothingShoesColorWhite
    eyes: ClothingEyesGlassesMeson
    id: AtmosPDA
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  innerClothingSkirt: ClothingUniformJumpskirtAtmos
  satchel: ClothingBackpackSatchelAtmosphericsFilled
  duffelbag: ClothingBackpackDuffelAtmosphericsFilled
