#Delta-V - This file is licensed under AGPLv3
# Copyright (c) 2024 Delta-V Contributors
# See AGPLv3.txt for details.

- type: startingGear
  id: RadioGuardGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack
    shoes: ClothingShoesBootsLaceup
    id: SyndiListeningPostPDA
    ears: ClothingHeadsetAltSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorPlateCarrierUnremoveable

- type: entity
  parent: ClothingOuterArmorPlateCarrier
  id: ClothingOuterArmorPlateCarrierUnremoveable
  name: grafted plate carrier
  suffix: Unremoveable
  description: An off-the-shelf plate carrier that has been cruelly grafted onto its wearers body
  noSpawn: true
  components:
    - type: Unremoveable  
