# Delta-V - This file is licensed under AGPLv3
# Copyright (c) 2024 Delta-V Contributors
# See AGPLv3.txt for details.

- type: entity
  parent: GunSafe
  id: GunSafePistolUniversal
  name: mk32 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolUniversal
      amount: 2
    - id: MagazineUniversalMagnum
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeSniperGrand
  name: mark 1 rifle safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSniperGrand
      amount: 2
    - id: SpeedLoaderLightRifle
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeVulcanRifle
  name: vulcan safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleVulcan
      amount: 2
    - id: MagazineLightRifle
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeAdjutantShotgun
  name: adjutant safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunAdjutant
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeEnergyGun
  name: energy gun safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponEnergyGun
      amount: 3

- type: entity
  parent: GunSafe
  id: GunSafeEnergyGunMini
  name: miniature energy gun safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponEnergyGunMini
      amount: 3
