- type: job
  id: Boxer
  name: job-name-boxer
  description: job-description-boxer
  playTimeTracker: JobBoxer
  startingGear: BoxerGear
  icon: "JobIconBoxer"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  # Begin DeltaV Additions
  - Theatre # Boxer is vaguely a theatre role
  - Boxer
  # End DeltaV Additions
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: BoxingDay
    prototype: ClothingHandsGlovesBoxingRigged

- type: startingGear
  id: BoxerGear
  equipment:
    id: BoxerPDA
    ears: ClothingHeadsetService
    shoes: ClothingShoesColorRed
    belt: ClothingBeltChampion
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: BoxerChameleonOutfit
  job: Boxer
  equipment:
    head: ClothingHeadHatBlacksoft
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterWinterColorGray
    jumpsuit: UniformShortsRedWithTop
    neck: ClothingNeckScarfStripedRed
