- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Psychologist # DeltaV - Add Psychologist access
  extendedAccess:
  - Chemistry

- type: startingGear
  id: PsychologistGear
  equipment:
    #shoes: ClothingShoesLeather # DeltaV - loadouts
    #id: PsychologistPDA # DeltaV - loadouts
    ears: ClothingHeadsetMedical
  storage:
    back:
    - RubberStampPsychologist
    - BoxFolderBlue # DeltaV

- type: chameleonOutfit
  id: PsychologistChameleonOutfit
  job: Psychologist
  equipment:
    head: ClothingHeadHatBeretMedic
    eyes: ClothingEyesHudMedical
    mask: ClothingMaskSterile
    outerClothing: ClothingOuterCoatLab
    neck: ClothingNeckStethoscope
    belt: ClothingBeltMedical
    gloves: ClothingHandsGlovesLatex
