- type: job
  id: Reporter
  name: job-name-reporter
  description: job-description-reporter
  playTimeTracker: JobReporter
  startingGear: ReporterGear
  icon: "JobIconReporter"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  # Begin DeltaV Additions
  - Theatre # Reporter is valuely a threatre role
  - Reporter
  # End DeltaV Additions

- type: startingGear
  id: ReporterGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: ReporterPDA
    ears: ClothingHeadsetService
  storage: # DeltaV: Give reporters tape recording equipment
    back:
    - TapeRecorder
    - CassetteTape
    - CassetteTape

- type: chameleonOutfit
  id: ReporterChameleonOutfit
  job: Reporter
  equipment:
    head: ClothingHeadHatFedoraGrey
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    outerClothing: ClothingOuterCoatTrench
    neck: ClothingNeckTieRed
    gloves: ClothingHandsGlovesFingerless
