[game]
hostname         = "[EN][MRP] Delta-v (Î¨) | Apoapsis [US East 1]"
soft_max_players = 100

[server]
rules_file   = "Rules.txt"
rules_header = "ui-rules-header"

[whitelist]
enabled     = false
reason      = "whitelist-not-whitelisted"
min_players = 90

[shuttle]
emergency_early_launch_allowed = true

[hub]
tags = "lang:en-US,region:am_n_e,rp:med,no_tag_infer"

[atmos]
monstermos_rip_tiles = false
