[game]
hostname         = "[EN][MRP] Delta-v (Ψ) | Apoapsis [US East 1]"
soft_max_players = 100
desc = """\
This server focuses on shorter and more chaotic shifts - For longer and calmer shifts, check out Periapsis!\
A medium roleplay fork based around the mysterious Noösphere, featuring unique content, custom maps, new species and a revamped science department.\
"""

[hub]
tags = "lang:en-US,region:am_n_e,rp:med,no_tag_infer"
