[game]
desc               = "A medium roleplay fork based around the mysterious No√∂sphere, featuring unique content, custom maps, new species and a revamped science department."
lobbyenabled       = true
lobbyduration      = 240
round_end_pacifist = true
contraband_examine = false # Doubtful that it's desired at all, and would require going over every item in accordance with SOP

[infolinks]
discord    = "https://discord.gg/deltav"
github     = "https://github.com/DeltaV-Station/Delta-v"
#website    = "https://www.delta-v.org/"
wiki       = "https://wiki.delta-v.org/view/Main_Page"
#patreon    = "https://www.patreon.com/Delta_v"
bug_report = "https://github.com/DeltaV-Station/Delta-v/issues/new/choose"
#forum      = "https://forum.delta-v.org/"
appeal     = "https://discord.gg/deltav"

[net]
max_connections = 1024
tickrate = 30

[vote]
restart_required_ratio = 0.7

[netres]
limit    = 10.0

[admin]
see_own_notes   = true
deadmin_on_join = true
alert.min_players_sharing_connection = 2

[server]
id         = "deltav"
rules_file = "DeltaVRuleset"

[discord]
rich_main_icon_id = "deltav"

[ic]
flavor_text = true

#[worldgen]
#enabled = true

[ahelp]
admin_prefix = false
admin_prefix_webhook = false
