[game]
hostname         = "[EN][MRP] Delta-v (Î¨) | Horizon [US East 3]"
soft_max_players = 80

[vote]
preset_enabled = true
map_enabled = true

[shuttle]
emergency_early_launch_allowed = true

[ooc]
enable_during_round = true

[hub]
tags = "lang:en-US,region:am_n_e,rp:med,no_tag_infer"
