[game]
hostname         = "[EN][MRP] Delta-v (Î¨) | Periapsis [US East 2]"
soft_max_players = 50

[server]
rules_file   = "Rules.txt"
rules_header = "ui-rules-header"

[vote]
preset_enabled = true
map_enabled = true

[whitelist]
enabled     = false
reason      = "whitelist-not-whitelisted-peri"
min_players = 25

[ooc]
enable_during_round = true

[hub]
tags = "lang:en-US,region:am_n_e,rp:med,no_tag_infer"
