[game]
hostname           = "[EN][MRP] Delta-v (Î¨) | Periapsis [US East 2]"
soft_max_players   = 50
round_restart_time = 300

[server]
rules_file   = "DeltaVRuleset"

[vote]
preset_enabled = true
map_enabled = true

[whitelist]
# TODO: make a whitelist prototype whenever this gets reenabled
enabled     = false

[ooc]
enable_during_round = true

[votekick]
enabled = true

[hub]
tags = "lang:en-US,region:am_n_e,rp:med,no_tag_infer"
