[game]
hostname           = "[EN][MRP] Delta-v (Ψ) | Periapsis [US East 2]"
soft_max_players   = 60
desc = """\
A medium roleplay fork based around the mysterious Noösphere, featuring unique content, custom maps, new species and a revamped science department.\
This server focuses on calmer shifts.\
"""

[vote]
preset_enabled = true
map_enabled = true

[whitelist]
# TODO: make a whitelist prototype whenever this gets reenabled
enabled     = false

[shuttle]
auto_call_time = 150 # 2.5 hours
auto_call_extension_time = 30 # next auto call at 3h00, gamers gotta game

[ooc]
enable_during_round = true

[votekick]
enabled = true

[hub]
tags = "lang:en-US,region:am_n_e,rp:med,no_tag_infer"

[discord]
round_end_role=1440055204451188847

[debug]
pow3r_disable_parallel = false
