[game]
hostname         = "[EN][MRP] Delta-v (Î¨) | Periapsis"
soft_max_players = 50

[server]
rules_file   = "Rules.txt"
rules_header = "ui-rules-header"

[whitelist]
enabled     = false
reason      = "whitelist-not-whitelisted"
min_players = 40

[ooc]
enable_during_round = true

[hub]
tags = "lang:en-US,region:am_n_e,rp:med"
