- type: job
  id: Borgmed
  name: "борг медицинский"
  description: job-description-borg
  playTimeTracker: JobBorgmed
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 1
  canBeAntag: false
  icon: JobIconBorgMedical
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgMedical
  startingGear: RobotGear # for char preview only
