- type: job
  id: Borgeng
  name: "борг инженерный"
  description: job-description-borg
  playTimeTracker: JobBorgeng
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 1
  canBeAntag: false
  icon: JobIconBorgEngineer
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgEngineer
  startingGear: RobotGear # for char preview only
