- type: job
  id: Roboticist
  name: "робототехник"
  description: "Бип-Буп."
  playTimeTracker: JobRoboticist
  requirements:
    - !type:DepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      time: 1
  startingGear: RoboticistGear
  icon: "JobIconRoboticist"
  supervisors: job-supervisors-rd
  access:
  - Research
  - Maintenance

- type: startingGear
  id: RoboticistGear
  equipment:
    belt: ClothingBeltUtilityFilled
    id: SciencePDA
    ears: ClothingHeadsetRobotics
    pocket1: StorageImplanter
    pocket2: HandheldStationMap
