- type: startingGear
  parent: CBURNGear
  id: CBURNGearDeltaV
  equipment:
    pocket1: WeaponPistolUniversalIncendiary
    pocket2: WeaponAdvancedLaser
    belt: ClothingBeltMilitaryWebbing
  storage:
    back:
    - WeaponShotgunKammererIncendiary
    - BoxShotgunIncendiary
    - BoxShotgunIncendiary
    - MagazineBoxMagnumIncendiary
    - MagazineBoxMagnumIncendiary
    - PillAmbuzolPlus
    - PillAmbuzol
    belt:
    - MagazineUniversalMagnumIncendiary
    - MagazineUniversalMagnumIncendiary
    - GrenadeFlashBang
    - GrenadeFlashBang
    - GrenadeFlashBang
