- type: job
  id: Courier
  name: job-name-courier
  description: job-description-courier
  startingGear: CourierGear
  playTimeTracker: JobCourier
  icon: "JobIconCourier"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  - Mail

- type: startingGear
  id: CourierGear
  equipment:
    id: MailCarrierPDA
    ears: ClothingHeadsetCargo
    belt: CourierBag
