- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage
  - Orders # DeltaV - Orders, see Resources/Prototypes/DeltaV/Access/cargo.yml

- type: startingGear
  id: CargoTechGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitCargo
    back: ClothingBackpackCargoFilled
    shoes: ClothingShoesColorBlack
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  innerClothingSkirt: ClothingUniformJumpskirtCargo
  satchel: ClothingBackpackSatchelCargoFilled
  duffelbag: ClothingBackpackDuffelCargoFilled
