- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  # Begin DeltaV modifications - Add time requirement to cargo tech
  # Uncomment once ready to deploy Cargo Assistant
  #requirements:
  #- !type:DepartmentTimeRequirement
  #  department: Logistics # DeltaV - Logistics Department replacing Cargo
  #  time: 21600 # 6 hrs ~3 shifts.
  # End DeltaV modifications
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  - Orders # DeltaV - Add Orders access to cargo techs.
  extendedAccess:
  - Salvage

- type: startingGear
  id: CargoTechGear
  equipment:
    #id: CargoPDA # DeltaV: different PDAs in loadouts
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
  #storage:
    #back:
    #- Stuff
