- type: job
  id: CargoTechnician
  name: job-name-cargotech
  description: job-description-cargotech
  playTimeTracker: JobCargoTechnician
  antagAdvantage: 2 # DeltaV - Reduced TC: External Access
  startingGear: CargoTechGear
  icon: "JobIconCargoTechnician"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  extendedAccess:
  - Salvage
  - Orders # DeltaV - Orders, see Resources/Prototypes/DeltaV/Access/cargo.yml

- type: startingGear
  id: CargoTechGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: CargoPDA
    ears: ClothingHeadsetCargo
    pocket1: AppraisalTool
