- type: job
  id: Quartermaster
  name: job-name-qm
  description: job-description-qm
  playTimeTracker: JobQuartermaster
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
  requirements:
    - !type:RoleTimeRequirement
      role: JobCargoTechnician
      time: 21600 #6 hrs
    - !type:RoleTimeRequirement
      role: JobSalvageSpecialist
      time: 10800 #3 hrs
    - !type:DepartmentTimeRequirement
      department: Logistics # DeltaV - Logistics department replacing Cargo
      time: 36000 #10 hours
    - !type:OverallPlaytimeRequirement
      time: 144000 #40 hrs
  weight: 10
  startingGear: QuartermasterGear
  icon: "JobIconQuarterMaster"
  requireAdminNotify: true # DeltaV
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Cargo
  - Salvage
  - Mail # Nyanotrasen - MailCarrier, see Resources/Prototypes/Nyanotrasen/Roles/Jobs/Cargo/mail-carrier.yml
  - Quartermaster
  - Maintenance
  - External
  - Command
  #- Brig # DeltaV - Removed brig access
  - Orders # DeltaV - Orders, see Resources/Prototypes/_DV/Access/cargo.yml
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: QuartermasterGear
  equipment:
    id: QuartermasterPDA
    ears: ClothingHeadsetQM
    belt: BoxFolderClipboard
    pocket1: AppraisalTool
  storage:
    back:
    - Flash
