
- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleConspirator
  name: Conspirator Role
  components:
  - type: ConspiratorRole
  - type: MindRole
    antagPrototype: Conspirator
    exclusiveAntag: true
    roleType: TeamAntagonist
    subtype: role-subtype-conspirator
