# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuit
  equipment: HeadofSecurityJumpsuit

- type: startingGear
  id: HeadofSecurityJumpsuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoS

- type: loadout
  id: HeadofSecurityJumpskirt
  equipment: HeadofSecurityJumpskirt

- type: startingGear
  id: HeadofSecurityJumpskirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoS

- type: loadout # DeltaV
  id: HeadofSecurityJumpsuitGrey
  equipment: HeadofSecurityJumpsuitGrey

- type: startingGear # DeltaV
  id: HeadofSecurityJumpsuitGrey
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSGrey

- type: loadout # DeltaV
  id: HeadofSecurityJumpskirtGrey
  equipment: HeadofSecurityJumpskirtGrey

- type: startingGear # DeltaV
  id: HeadofSecurityJumpskirtGrey
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSGrey

- type: loadout # DeltaV
  id: HeadofSecurityJumpsuitBlue
  equipment: HeadofSecurityJumpsuitBlue

- type: startingGear # DeltaV
  id: HeadofSecurityJumpsuitBlue
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSBlue

- type: loadout # DeltaV
  id: HeadofSecurityJumpskirtBlue
  equipment: HeadofSecurityJumpskirtBlue

- type: startingGear # DeltaV
  id: HeadofSecurityJumpskirtBlue
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSBlue

- type: loadout
  id: HeadofSecurityTurtleneck
  equipment: HeadofSecurityTurtleneck

- type: startingGear
  id: HeadofSecurityTurtleneck
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSAlt

- type: loadout
  id: HeadofSecurityTurtleneckSkirt
  equipment: HeadofSecurityTurtleneckSkirt

- type: startingGear
  id: HeadofSecurityTurtleneckSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSAlt

- type: loadout
  id: HeadofSecurityFormalSuit
  equipment: HeadofSecurityFormalSuit

- type: startingGear
  id: HeadofSecurityFormalSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHosFormal

- type: loadout
  id: HeadofSecurityFormalSkirt
  equipment: HeadofSecurityFormalSkirt

- type: startingGear
  id: HeadofSecurityFormalSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHosFormal

# Head
- type: loadout
  id: HeadofSecurityHead
  equipment: HeadofSecurityHead

- type: startingGear
  id: HeadofSecurityHead
  equipment:
    head: ClothingHeadHatHoshat

- type: loadout
  id: HeadofSecurityBeret
  equipment: HeadofSecurityBeret

- type: startingGear
  id: HeadofSecurityBeret
  equipment:
    head: ClothingHeadHatBeretHoS

# Neck
- type: loadout
  id: HeadofSecurityCloak
  equipment: HeadofSecurityCloak

- type: startingGear
  id: HeadofSecurityCloak
  equipment:
    neck: ClothingNeckCloakHos

- type: loadout
  id: HeadofSecurityMantle
  equipment: HeadofSecurityMantle

- type: startingGear
  id: HeadofSecurityMantle
  equipment:
    neck: ClothingNeckMantleHOS

# OuterClothing
- type: loadout # DeltaV
  id: HoSStasecCoat
  equipment: HoSStasecCoat

- type: startingGear # DeltaV
  id: HoSStasecCoat
  equipment:
    outerClothing: ClothingOuterStasecCoatHoS

- type: loadout # DeltaV
  id: HeadofSecurityCoat
  equipment: HeadofSecurityCoat

- type: startingGear # DeltaV
  id: HeadofSecurityCoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout # DeltaV
  id: HeadofSecurityWinterCoat
  equipment: HeadofSecurityWinterCoat

- type: startingGear # DeltaV
  id: HeadofSecurityWinterCoat
  equipment:
    outerClothing: ClothingOuterWinterHoS

# Shoes - DeltaV
- type: loadout # DeltaV
  id: HeadOfSecurityWinterBoots
  equipment: HeadOfSecurityWinterBoots

- type: startingGear # DeltaV
  id: HeadOfSecurityWinterBoots
  equipment:
    shoes: ClothingShoesBootsWinterHeadOfSecurity