- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleListeningPost
  name: Listening Post Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    subtype: role-subtype-lpo
    antagPrototype: ListeningPost
    exclusiveAntag: true
  - type: ListeningPostRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleFugitive
  name: Fugitive Role
  components:
  - type: MindRole
    subtype: role-subtype-fugitive
    antagPrototype: Fugitive
    exclusiveAntag: true
  - type: FugitiveRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleRecruiter
  name: Recruiter Role
  components:
  - type: MindRole
    subtype: role-subtype-recruiter
    antagPrototype: Recruiter
    exclusiveAntag: true
  - type: RecruiterRole
  - type: RoleBriefing
    briefing: recruiter-role-briefing

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSynthesis
  name: Synthesis Specialist Role
  components:
  - type: MindRole
    roleType: FreeAgent
    subtype: role-subtype-synthesis
    antagPrototype: SynthesisSpecialist
    exclusiveAntag: true
  - type: SynthesisRole
  - type: RoleBriefing
    briefing: synthesis-role-briefing

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleRoboNeuroticist
  name: Robo-Neuroticist Role
  components:
  - type: MindRole
    subtype: role-subtype-roboneuro
    antagPrototype:  RoboNeuroticist
    exclusiveAntag: true
  - type: RoboNeuroticistRole
  - type: RoleBriefing
    briefing: roboneuroticist-role-briefing

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleMenaceSkeleton
  name: Menace Skeleton Role
  components:
  - type: MindRole
    roleType: FreeAgent
    antagPrototype: MenaceSkeleton
    exclusiveAntag: true
  - type: MenaceSkeletonRole
  - type: RoleBriefing
    briefing: skeleton-role-briefing

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSkia
  name: Skia Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    antagPrototype: Skia
    exclusiveAntag: true
  - type: SkiaRole
  - type: RoleBriefing
    briefing: skia-role-briefing

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleArmsdealer
  name: Arms Dealer Role
  components:
  - type: MindRole
    roleType: FreeAgent
    subtype: role-subtype-armsdealer
    antagPrototype: SyndicateArmsdealer
    exclusiveAntag: true
  - type: ArmsdealerRole
  - type: RoleBriefing
    briefing: armsdealer-role-briefing

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleAsakim
  name: Asakim Role
  components:
  - type: MindRole
    roleType: FreeAgent
    subtype: role-subtype-asakim
    antagPrototype: Asakim
    exclusiveAntag: true
  - type: AsakimRole
  - type: RoleBriefing
    briefing: asakim-role-briefing

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleNTAgent
  name: Internals Affairs Agent
  components:
  - type: MindRole
    roleType: FreeAgent
    subtype: role-subtype-ntagent
    antagPrototype: NTAgent
    exclusiveAntag: true
  - type: NTAgentRole
  - type: RoleBriefing
    briefing: NTAgent-briefing
