- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleListeningPost
  name: Listening Post Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    antagPrototype: ListeningPost
    exclusiveAntag: true
  - type: ListeningPostRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleParadoxAnomaly
  name: Paradox Anomaly Role
  components:
  - type: MindRole
    roleType: SoloAntagonist
    antagPrototype: ParadoxAnomaly
    exclusiveAntag: true
  - type: ParadoxAnomalyRole
  - type: RoleBriefing
    briefing: paradox-anomaly-role-briefing

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleFugitive
  name: Fugitive Role
  components:
  - type: MindRole
    roleType: SoloAntagonist
    antagPrototype: Fugitive
    exclusiveAntag: true
  - type: FugitiveRole

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleRecruiter
  name: Recruiter Role
  components:
  - type: MindRole
    roleType: SoloAntagonist
    antagPrototype: Recruiter
    exclusiveAntag: true
  - type: RecruiterRole
  - type: RoleBriefing
    briefing: recruiter-role-briefing

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleSynthesis
  name: Synthesis Specialist Role
  components:
  - type: MindRole
    roleType: TeamAntagonist
    antagPrototype: SynthesisSpecialist
    exclusiveAntag: true
  - type: SynthesisRole
  - type: RoleBriefing
    briefing: synthesis-role-briefing

- type: entity
  parent: BaseMindRoleAntag
  id: MindRoleRoboNeuroticist
  name: Robo-Neuroticist Role
  components:
  - type: MindRole
    roleType: SoloAntagonist
    antagPrototype:  RoboNeuroticist
    exclusiveAntag: true
  - type: RoboNeuroticistRole
  - type: RoleBriefing
    briefing: roboneuroticist-role-briefing
