- type: job
  id: CBURN
  name: job-name-cburn
  description: job-description-cburn
  playTimeTracker: JobCBURN
  setPreference: false
  startingGear: CBURNGearDeltaV # DeltaV - Different startingGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  requirements: # DeltaV - Playtime requirements
  - !type:DepartmentTimeRequirement
    department: Security
    time: 10h
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 5h
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ CentCommImplant, DeathRattleImplantCentcomm ] # Delta-V - Changed Mindshield implant to Centcomm implant

- type: startingGear
  id: CBURNGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBrown
    back: ClothingBackpackDuffelCBURN
    mask: ClothingMaskGasERT
    eyes: ClothingEyesGlassesSecurity
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitCBURN
    shoes: ClothingShoesBootsCombatFilled
    id: CBURNPDA
    pocket1: RadioHandheld
    pocket2: WeaponLaserGun
    belt: ClothingBeltBandolier
  storage:
    back:
    - WeaponShotgunDoubleBarreled
    - BoxShotgunIncendiary
    - GrenadeFlashBang
    - PillAmbuzolPlus
    - PillAmbuzol

- type: chameleonOutfit
  id: CBURNChameleonOutfit
  job: CBURN
  hasMindShield: true
  equipment:
    head: ClothingHeadHelmetCBURN
    neck: ClothingNeckScarfStripedBrown
