- type: job
  id: MartialArtist
  name: job-name-martialartist
  description: job-description-martialartist
  playTimeTracker: JobMartialArtist
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 2h
  startingGear: MartialArtistGear
  icon: "JobIconMartialArtist"
  supervisors: job-supervisors-hop
  setPreference: true
#  whitelistRequired: true
  access:
  - Maintenance
  - Theatre # DeltaV - Add Theatre access
  - Boxer # DeltaV - Add Boxer access

- type: startingGear
  id: MartialArtistGear
  equipment:
    id: MartialArtistPDA
    ears: ClothingHeadsetService

- type: chameleonOutfit
  id: MartialArtistChameleonOutfit
  job: MartialArtist
  equipment:
    id: MartialArtistPDA
    ears: ClothingHeadsetService
    jumpsuit: ClothingUniformMartialGi
    shoes: ClothingShoesGeta
