- type: job
  id: MedicalBorg
  name: job-name-medical-borg
  description: job-description-medical-borg
  playTimeTracker: JobMedicalBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 60h
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 6h
  canBeAntag: false
  icon: JobIconMedicalBorg
  supervisors: job-supervisors-cmo
  jobEntity: PlayerBorgMedical
  applyTraits: false
