- type: job
  id: Surgeon
  name: job-name-surgeon
  description: job-description-surgeon
  playTimeTracker: JobSurgeon
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 8h
  startingGear: SurgeonGear
  icon: JobIconSurgeon
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Surgery
  - Maintenance

- type: startingGear
  id: SurgeonGear
  equipment:
    ears: ClothingHeadsetMedical
    belt: ClothingBeltSurgeonFilled

- type: chameleonOutfit
  id: SurgeonChameleonOutfit
  job: Surgeon
  equipment:
    id: SurgeonPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltSurgeonFilled
    head: ClothingHeadHatSurgcapCyan
    jumpsuit: UniformScrubsColorCyan
