- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  requirements:
  - !type:OverallPlaytimeRequirement #DeltaV
    time: 3600 #1h
  startingGear: BartenderGear
  icon: "JobIconBartender"
  setPreference: false
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics

- type: startingGear
  id: BartenderGear
  equipment:
    shoes: ClothingShoesColorBlack
    #id: BartenderPDA # DeltaV - different PDAs in loadouts
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
