- type: job
  id: Bartender
  name: job-name-bartender
  description: job-description-bartender
  playTimeTracker: JobBartender
  antagAdvantage: 1 # DeltaV - Shotgun, and free room
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3600 # DeltaV
  startingGear: BartenderGear
  icon: "JobIconBartender"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Bar
  extendedAccess:
  - Kitchen
  - Hydroponics

- type: startingGear
  id: BartenderGear
  equipment:
    shoes: ClothingShoesColorBlack
    #id: BartenderPDA # DeltaV - different PDAs in loadouts
    ears: ClothingHeadsetService
  #storage:
    #back:
    #- Stuff
