- type: job
  id: Chaplain
  name: job-name-chaplain
  description: job-description-chaplain
  playTimeTracker: JobChaplain
  antagAdvantage: 2 # DeltaV - Increased Psionics, Gib machine
  startingGear: ChaplainGear
  icon: "JobIconChaplain"
  supervisors: job-supervisors-rd # DeltaV - Change supervisor to mystagogue
  canBeAntag: false # DeltaV - Can't be antag in case of Cultist antag presence. Remove this flag when antagselection is granularized.
  access:
  - Chapel
  - Research # DeltaV - Move Chaplain into Epistemics
  - Maintenance
  special:
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
    - type: PsionicBonusChance # DeltaV - makes it more likely to become psionic.
      multiplier: 3

- type: startingGear
  id: ChaplainGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChaplainPDA
    ears: ClothingHeadsetScience # DeltaV - Move Chaplain into Epistemics
  storage:
    back:
    - Bible
    - RubberStampChaplain

- type: chameleonOutfit
  id: ChaplainChameleonOutfit
  job: Chaplain
  equipment:
    head: ClothingHeadHatPlaguedoctor
    eyes: ClothingEyesGlasses
    mask: ClothingMaskPlague
    neck: ClothingNeckStoleChaplain
    outerClothing: ClothingOuterPlagueSuit
    gloves: ClothingHandsGlovesColorBlack

