- type: job
  id: Clown
  name: job-name-clown
  description: job-description-clown
  playTimeTracker: JobClown
  requirements:
    - !type:OverallPlaytimeRequirement # DeltaV - Playtime requirement
      time: 7200 #2 hrs
  startingGear: ClownGear
  icon: "JobIconClown"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  - Clown # DeltaV - Add Clown access
  - Service # DeltaV - They work in service don't they?
  special:
  - !type:AddComponentSpecial
    components:
    - type: Clumsy
      gunShootFailDamage:
        types: #literally just picked semi random valus. i tested this once and tweaked it.
          Blunt: 5
          Piercing: 4
        groups:
          Burn: 3
# DeltaV - Commenting out the clown snore sound because I am not fond of it (it makes me itchy and feral). By "I", I mean Leonardo_DaBepis.
#    - type: SleepEmitSound
#      snore: /Audio/Voice/Misc/silly_snore.ogg
#      interval: 10
  - !type:AddImplantSpecial
    implants: [ SadTromboneImplant ]

- type: startingGear
  id: ClownGear
  equipment:
    mask: ClothingMaskClown
    pocket1: BikeHorn
    pocket2: ClownRecorder
    #id: ClownPDA # DeltaV: different PDAs in loadouts
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampClown
    - CrayonRainbow
