- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  antagAdvantage: 4 # DeltaV - Reduced TC: Security Radio and Access
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 2.5h
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-cj # DeltaV - Change supervisor to chief justice
  access:
  - Justice # DeltaV - Justice dept, replaces Service
  - Lawyer
  #- Brig # DeltaV - Removed brig access
  - Maintenance
  special: # Goobstation - Everyone knows lawyers are soulless.
  - !type:AddComponentSpecial
    components:
    - type: Condemned
      soulOwnedNotDevil: true

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetJustice # DeltaV - Added lawyer to justice department
  inhand:
    - BriefcaseBrownFilled
  storage:
    back:
    - RubberStampLawyer
    - BookSpaceLaw
    - ForensicScanner # DeltaV - lets lawyers grab evidence

- type: chameleonOutfit
  id: LawyerChameleonOutfit
  job: Lawyer
  equipment:
    head: ClothingHeadHatBowlerHat
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskBreath
    neck: ClothingNeckLawyerbadge
    outerClothing: ClothingOuterWinterColorBlack
    gloves: ClothingHandsGlovesColorBlack
