- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  antagAdvantage: 2 # DeltaV - Reduced TC: Security Radio and Access
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 36000 # 10 hrs
    - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
      department: Security
      time: 14400 # 4 hours
  startingGear: LawyerGear
  icon: "JobIconLawyer"
  supervisors: job-supervisors-cj  # Delta V - Change supervisor to chief justice
  access:
  - Service
  - Lawyer
  - Justice # Delta V - Add justice departement access
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitLawyerBlack  # TODO change jumpsuit to randomiser of the 4 variants
    back: ClothingBackpackLawyerFilled #DeltaV - stamp included
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
    # TODO add copy of space law
  inhand:
    - BriefcaseBrownFilled
  innerClothingSkirt: ClothingUniformJumpskirtLawyerBlack
  satchel: ClothingBackpackSatchelLawyerFilled #DeltaV - stamp included
  duffelbag: ClothingBackpackDuffelLawyerFilled #DeltaV - stamp included
