- type: job
  id: Mime
  name: job-name-mime
  description: job-description-mime-delta # DeltaV
  playTimeTracker: JobMime
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 4h
  startingGear: MimeGear
  icon: "JobIconMime"
  supervisors: job-supervisors-hop
  access:
  - Theatre
  - Maintenance
  - Mime # DeltaV - Add Mime access
  - Service # DeltaV - They work in service don't they?
  special:
  - !type:AddComponentSpecial
    components:
    - type: Psionic # Nyano - Summary: Makes the mime psionic.
    - type: MimePowers
      preventWriting: false # DeltaV
    - type: FrenchAccent

- type: startingGear
  id: MimeGear
  equipment:
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesColorWhite
    id: MimePDA
    pocket1: CrayonMime
    pocket2: Paper # DeltaV
    ears: ClothingHeadsetService
  storage:
    back:
    - RubberStampMime

- type: entity
  parent: BaseAction
  id: ActionMimeInvisibleWall
  name: Create Invisible Wall
  description: Create an invisible wall in front of you, if placeable there.
  components:
  - type: Action
    priority: -1
    useDelay: 30
    icon:
      sprite: Structures/Walls/solid.rsi
      state: full
  - type: InstantAction
    event: !type:InvisibleWallActionEvent

- type: chameleonOutfit
  id: MimeChameleonOutfit
  job: Mime
  equipment:
    head: ClothingHeadHatMimesoft
    eyes: ClothingEyesGlassesCheapSunglasses
    neck: ClothingNeckScarfStripedZebra
    outerClothing: ClothingOuterWinterMime
