# Jumpsuit
- type: loadout
  id: HeadofSecurityJumpsuitGrey
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSGrey

- type: loadout
  id: HeadofSecurityJumpskirtGrey
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSGrey

- type: loadout
  id: HeadofSecurityJumpsuitBlue
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSBlue

- type: loadout
  id: HeadofSecurityJumpskirtBlue
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSBlue

- type: loadout
  id: HeadofSecurityParadeSuit
  equipment:
    jumpsuit: ClothingUniformJumpsuitHoSParadeMale

- type: loadout
  id: HeadofSecurityParadeSkirt
  equipment:
    jumpsuit: ClothingUniformJumpskirtHoSParadeMale

# OuterClothing
- type: loadout
  id: StasecWinterCoatHoS
  equipment:
    outerClothing: ClothingOuterCoatStasecHoS

- type: loadout
  id: HeadOfSecurityTrenchcoat
  equipment:
    outerClothing: ClothingOuterCoatHoSTrench

- type: loadout
  id: HeadofSecurityLongcoat
  equipment:
    outerClothing: ClothingLongcoatHoS

# Shoes
- type: loadout
  id: HeadOfSecurityWinterBoots
  equipment:
    shoes: ClothingShoesBootsWinterHeadOfSecurity
