- type: entity
  parent: GunSafeHandgunDV
  id: GunSafePistolUniversal
  name: mk32 safe
  components:
  - type: EntityStorageVisuals
    stateDoorClosed: pistol
  - type: StorageFill
    contents:
    - id: WeaponPistolUniversal
      amount: 2
    - id: MagazineUniversalMagnum
      amount: 4

- type: entity
  parent: GunSafeBaseSecureDV
  id: GunSafeSniperGrand
  name: mark 1 rifle safe
  components:
  - type: EntityStorageVisuals
    stateDoorClosed: sniper
  - type: StorageFill
    contents:
    - id: WeaponSniperGrand
      amount: 2
    - id: SpeedLoaderLightRifle
      amount: 4

- type: entity
  parent: GunSafeBaseSecureDV
  id: GunSafeVulcanRifle
  name: vulcan safe
  components:
  - type: EntityStorageVisuals
    stateDoorClosed: vulcan
  - type: StorageFill
    contents:
    - id: WeaponRifleVulcan
      amount: 2
    - id: MagazineLightRifle
      amount: 4

- type: entity
  parent: GunSafeBaseSecureDV
  id: GunSafeAdjutantShotgun
  name: adjutant safe
  components:
  - type: EntityStorageVisuals
    stateDoorClosed: rifle
  - type: StorageFill
    contents:
    - id: WeaponShotgunAdjutant
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  parent: GunSafeBaseSecureDV
  id: GunSafeEnergyGun
  name: energy gun safe
  components:
  - type: EntityStorageVisuals
    stateDoorClosed: energy
  - type: StorageFill
    contents:
    - id: WeaponEnergyGun
      amount: 3

- type: entity
  parent: GunSafeBaseSecureDV
  id: GunSafeEnergyGunMini
  name: miniature energy gun safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponEnergyGunMini
      amount: 3

- type: entity
  parent: GunSafeBaseSecureDV
  id: GunSafeM90Rifle
  name: M-90 rifle safe
  components:
  - type: EntityStorageVisuals
    stateDoorClosed: m90
  - type: StorageFill
    contents:
    - id: WeaponRifleM90
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: GunSafeSuperweaponBaseSecureDV
  id: GunSafeRocketLauncher
  name: RPG safe
  components:
  - type: EntityStorageVisuals
    stateDoorClosed: rpg
  - type: StorageFill
    contents:
    - id: WeaponLauncherRocket
    - id: CartridgeRocket
      prob: 0.2

- type: entity
  parent: GunSafeSuperweaponBaseSecureDV
  id: GunSafeBeamDevastator
  name: Devastator safe
  components:
  - type: EntityStorageVisuals
    stateDoorClosed: devastator
  - type: StorageFill
    contents:
    - id: WeaponBeamDevastator

- type: entity
  parent: GunSafeSuperweaponBaseSecureDV
  id: GunSafeGamblagator
  name: Gamblagator safe
  components:
  - type: EntityStorageVisuals
    stateDoorClosed: gamblagator
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: GamblagatorTable

- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Corpsman, Filled, Hardsuit
  parent: LockerBrigmedic
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerBrigmedic
        - !type:NestedSelector
          tableId: LockerFillBrigmedicHardsuit

- type: entityTable
  id: LockerFillBrigmedicHardsuit
  table: !type:AllSelector
    children:
    - id: ClothingOuterHardsuitCombatCorpsman
    - id: ClothingShoesBootsSecurityMagboots
    - id: OxygenTankFilled
    - id: ClothingMaskBreath

- type: entity
  parent: GunSafeNonlethalDV
  id: GunSafeNonLethalShotgun
  name: non-lethal shotgun safe
  suffix: Security, Locked
  components:
  - type: EntityStorageVisuals
    stateDoorClosed: shotgun
  - type: AccessReader
    access: [["Security"]]
  - type: StorageFill
    contents:
    - id: WeaponShotgunKammererNonLethal
      amount: 2
    - id: BoxBeanbag
      amount: 2
    - id: BoxShotgunPractice
      amount: 2

- type: entity
  parent: GunSafeBaseSecureDV
  id: GunSafeSubMachineGunPatos
  name: patos safe
  components:
  - type: EntityStorageVisuals
    stateDoorClosed: smg
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunPatos
      amount: 2
    - id: MagazinePistolHighCapacity
      amount: 4
