- type: entity
  parent: GunSafeBaseSecure
  id: GunSafePistolUniversal
  name: mk32 safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: WeaponPistolUniversal
          amount: 2
        - id: MagazineUniversalMagnum
          amount: 4

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeSniperGrand
  name: mark 1 rifle safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: WeaponSniperGrand
          amount: 2
        - id: SpeedLoaderLightRifle
          amount: 4

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeVulcanRifle
  name: vulcan safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: WeaponRifleVulcan
          amount: 2
        - id: MagazineLightRifle
          amount: 4

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeAdjutantShotgun
  name: adjutant safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: WeaponShotgunAdjutant
          amount: 2
        - id: MagazineShotgun
          amount: 4

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeEnergyGun
  name: energy gun safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: WeaponEnergyGun
        amount: 3

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeEnergyGunMini
  name: miniature energy gun safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: WeaponEnergyGunMini
        amount: 3

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeM90Rifle
  name: M-90 rifle safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: WeaponRifleM90
          amount: 2
        - id: MagazineRifle
          amount: 4

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeRocketLauncher
  name: RPG safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: WeaponLauncherRocket
        - id: CartridgeRocket
          prob: 0.2

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeBeamDevastator
  name: Devastator safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage:
        id: WeaponBeamDevastator

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeGamblagator
  name: Gamblagator safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: GamblagatorTable

- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Corpsman, Filled, Hardsuit
  parent: LockerBrigmedic
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerBrigmedic
        - !type:NestedSelector
          tableId: LockerFillBrigmedicHardsuit

- type: entityTable
  id: LockerFillBrigmedicHardsuit
  table: !type:AllSelector
    children:
    - id: ClothingOuterHardsuitCombatCorpsman
    - id: ClothingShoesBootsSecurityMagboots
    - id: OxygenTankFilled
    - id: ClothingMaskBreath

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeNonLethalShotgun
  name: non-lethal shotgun safe
  suffix: Security, Locked
  components:
  - type: AccessReader
    access: [["Security"]]
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: WeaponShotgunKammererNonLethal
          amount: 2
        - id: BoxBeanbag
          amount: 2
        - id: BoxShotgunPractice
          amount: 2

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeSubMachineGunPatos
  name: patos safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - id: WeaponSubMachineGunPatos
          amount: 2
        - id: MagazinePistolHighCapacity
          amount: 4
