- type: job
  id: PrisonGuard
  name: job-name-guard
  description: job-description-guard
  playTimeTracker: JobPrisonGuard
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 5h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 4h
  startingGear: PrisonGuardGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "JobIconPrisonGuard"
  supervisors: job-supervisors-warden
  setPreference: true
  access:
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  - External # DeltaV - Added external access
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]


- type: startingGear
  id: PrisonGuardGear
  equipment:
    #eyes: ClothingEyesGlassesSecurity # DeltaV - loadouts
    id: PrisonGuardPDA
    ears: ClothingHeadsetPrisonGuard # begin DeltaV
  storage:
    back:
    - Flash
   # - MagazinePistol # end DeltaV

# DeltaV
- type: chameleonOutfit
  id: PrisonGuardChameleonOutfit
  job: PrisonGuard
  hasMindShield: true
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: PrisonGuardPDA
    ears: ClothingHeadsetPrisonGuard
    head: ClothingHeadPrisonGuard
    jumpsuit: ClothingUniformJumpsuitPrisonGuard
    mask: ClothingMaskGasSecurity
    gloves: ClothingHandsGlovesColorBlack

