- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 6h
    - !type:RoleTimeRequirement # DeltaV - JobSecurityOfficer time requirement
      role: JobSecurityOfficer
      time: 6h
  startingGear: CorpsmanGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  - External
  - Corpsman
  extendedAccess:
  - Chemistry
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: CorpsmanGear # see Prototypes/Roles/Jobs/Fun/misc_startinggear.yml for "BrigmedicGear"
  equipment:
    #eyes: ClothingEyesHudMedical # DeltaV - loadouts
    id: CorpsmanPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltCorpsmanWebbingFilled
 #  pocket1: WeaponPistolMk58Nonlethal # DeltaV - loadouts
  storage:
    back:
    #- EmergencyRollerBedSpawnFolded # DeltaV - moved to locker
    #- BodyBagFolded # DeltaV - moved to locker
    #- BruteAutoInjector # DeltaV - removed in favor of combat medkit
    #- BruteAutoInjector
    #- BurnAutoInjector # DeltaV - removed in favor of combat medkit
    #- BurnAutoInjector
    #belt:
    #- Portafib
  #  - MagazinePistol # DeltaV - loadouts

- type: chameleonOutfit
  id: BrigMedicChameleonOutfit
  job: Brigmedic
  hasMindShield: true
  equipment:
    eyes: ClothingEyesHudMedical
    id: CorpsmanPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltCorpsmanWebbing
    jumpsuit: ClothingUniformJumpsuitBrigmedic
    back: ClothingBackpackBrigmedic
    outerClothing: ClothingOuterCoatStasecCorpsman
    head: ClothingHeadHatBeretCorpsman
    mask: ClothingMaskGasSecurity
    gloves: ClothingHandsGlovesColorBlack
