# Generic K9 role for secdogs
- type: job
  id: RoleK9Officer
  playTimeTracker: RoleK9Officer
  name: role-name-k9-officer
  description: role-description-k9-officer
  icon: JobIconSecurityK9Officer
  supervisors: job-supervisors-hos
  access:
  - Security
  - Maintenance
  canBeAntag: false
