- type: job
  id: SecurityBorg
  name: job-name-security-borg
  description: job-description-security-borg
  playTimeTracker: JobSecurityBorg
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 60h
    - !type:DepartmentTimeRequirement
      department: Security
      time: 20h
  canBeAntag: false
  icon: JobIconSecurityBorg
  supervisors: job-supervisors-everyone
  jobEntity: PlayerBorgSecurity
  applyTraits: false
