# No idea why it's in sci but we ball.
- type: job
  id: StationAi
  name: job-name-station-ai
  description: job-description-station-ai
  playTimeTracker: JobStationAi
  requirements:
    - !type:OverallPlaytimeRequirement #DeltaV
      time: 54000 # 15 h
    - !type:DepartmentTimeRequirement
      department: Command
      time: 18000 # 5 hours
    - !type:DepartmentTimeRequirement
      department: Silicon
      time: 18000  # 5 hrs
  canBeAntag: false
  #setPreference: false # DeltaV - disable AI until its fleshed out
  #whitelisted: true # DeltaV - ai must be whitelisted
  icon: JobIconStationAi
  supervisors: job-supervisors-rd
  jobEntity: StationAiBrain
  applyTraits: false
