- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
  requirements:
    - !type:DepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      time: 54000 # DeltaV - 15 hours
    - !type:OverallPlaytimeRequirement
      time: 72000 # DeltaV - 20 hours, was 40
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Mantis # DeltaV - Psionic Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
  - Chapel # DeltaV - Chaplain is in Epistemics
  - Robotics # DeltaV - Robotics access
  - External # DeltaV - AI satellite access
  - Cryogenics
  special: # Nyanotrasen - Mystagogue can use the Bible
  - !type:AddComponentSpecial
    components:
    - type: BibleUser # Nyano - Lets them heal with bibles
    - type: Psionic # Nyano - They start with telepathic chat
    - type: DispelPower # Nyano - They get the Dispel psionic power on spawn
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    id: RnDPDA
    ears: ClothingHeadsetRD
    belt: BibleMystagogue # Nyanotrasen - Mystagogue book for their Ifrit
  storage:
    back:
    - Flash
