- type: job
  id: ResearchDirector
  name: job-name-rd
  description: job-description-rd
  playTimeTracker: JobResearchDirector
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
  requirements:
    - !type:DepartmentTimeRequirement
      department: Science
      time: 54000 # DeltaV - 15 hours
    - !type:OverallPlaytimeRequirement
      time: 72000 # DeltaV - 20 hours
  weight: 10
  startingGear: ResearchDirectorGear
  icon: "JobIconResearchDirector"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Research
  - Command
  - Maintenance
  - ResearchDirector
  - Mantis # DeltaV - Psionic Mantis, see Resources/Prototypes/DeltaV/Access/epistemics.yml
  special: # Nyanotrasen - Mystagogue can use the Bible
  - !type:AddComponentSpecial
    components:
    - type: BibleUser #Lets them heal with bibles
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: ResearchDirectorGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitResearchDirector
    back: ClothingBackpackResearchDirectorFilled
    shoes: ClothingShoesColorBrown
    head: ClothingHeadHoodMystic # DeltaV - Mystagogue new hat
    outerClothing: ClothingOuterCoatRndMysta # DeltaV - Mystagogue new coat
    id: RnDPDA
    ears: ClothingHeadsetRD
  innerclothingskirt: ClothingUniformJumpskirtResearchDirector
  satchel: ClothingBackpackSatchelResearchDirectorFilled
  duffelbag: ClothingBackpackDuffelResearchDirectorFilled
