- type: job
  id: DAP
  name: job-name-dap
  description: job-description-dap
  playTimeTracker: JobDAP
  setPreference: false
  startingGear: DAPGear
  icon: "JobIconNanotrasen"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  access:
  - CentralCommand
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  requirements: # Same as Nukie Commander
  - !type:OverallPlaytimeRequirement
    time: 216000
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000
  - !type:DepartmentTimeRequirement
    department: Command
    time: 36000

- type: startingGear
  id: DAPGear # Reminder to change sprites for DS items
  equipment:
    jumpsuit: ClothingUniformJumpsuitDeathSquad
    back: ClothingBackpackDeathSquad
    mask: ClothingMaskGasDeathSquad
    eyes: ClothingEyesHudOmni
    ears: ClothingHeadsetAltCentCom
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitDeathsquad
    shoes: ClothingShoesBootsMagAdv
    id: DeathsquadPDA
    pocket1: EnergySword
    pocket2: EnergyShield
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - WeaponPulsePistol
    - WeaponRevolverMatebaAP
    - SpeedLoaderMagnumAP
    - SpeedLoaderMagnumAP
    - BoxFlashbang
    - Omnitool
    - WelderExperimental
    - Hypospray
    - DeathAcidifierImplanter
    - FreedomImplanter
    - ScramImplanter
  inhand:
  - WeaponPulseRifle
