- type: antag
  id: SpaceNinja
  name: roles-antag-space-ninja-name
  antagonist: true
  setPreference: false
  objective: roles-antag-space-ninja-objective
  requirements:
  - !type:OverallPlaytimeRequirement # DeltaV - Playtime requirement
    time: 36000 # DeltaV - 10 hours
