- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 30h # DeltaV - was 5h
  - !type:DepartmentTimeRequirement # DeltaV - engi dept time requirement
    department: Engineering
    time: 2h
  - !type:RoleTimeRequirement # DeltaV - salvage time requirement
    role: JobSalvageSpecialist
    time: 2h
  - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    time: 10h
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-corpsman-name # DeltaV
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-corpsman-objective # DeltaV
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 30h # DeltaV - was 5h
  - !type:RoleTimeRequirement # Delta V - they should be able to make basic chems
    role: JobChemist
    time: 4h # DeltaV
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  guides: [ NuclearOperatives ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 60h # DeltaV - was 5h
  - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    time: 10h # DeltaV - was 5h
  - !type:DepartmentTimeRequirement # DeltaV - Command dept time requirement
    department: Command
    time: 10h
  - !type:WhitelistRequirement # DeltaV - Whitelist requirement
  # should be changed to nukie playtime when thats tracked (wyci)

- type: startingGear
  id: SyndicateOperativeGearFullNoUplink
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiOperativePDA
    pocket2: PlushieCarp
    belt: ClothingBeltMilitaryWebbing
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    # - DeathAcidifierImplanter # DeltaV - more TC less acid
    - BionicVoiceMaskImplanter # DeltaV - Voice masking implant

#Nuclear Operative Gear
- type: startingGear
  id: SyndicateOperativeGearFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    pocket2: BaseUplinkRadio45TC # DeltaV - removal of armor
    outerClothing: ClothingOuterCoatSyndieCap # DeltaV - removal of armor

- type: chameleonOutfit
  id: NukeopsOutfit
  name: roles-antag-nuclear-operative-name
  startingGear: SyndicateOperativeGearFullNoUplink
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndie
    neck: ClothingNeckScarfStripedSyndieRed

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    id: SyndiCommanderPDA
    neck: SyndicateWhistle
    pocket2: CommanderUplinkRadio45TC # DeltaV - allows them to buy commander armor
    outerClothing: ClothingOuterCoatSyndieCapArmored # DeltaV - removal of armor
  inhand:
  - NukeOpsDeclarationOfWar

- type: chameleonOutfit
  id: NukeopsCommanderOutfit
  name: roles-antag-nuclear-operative-commander-name
  startingGear: SyndicateCommanderGearFull
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieCommander
    neck: ClothingNeckScarfStripedSyndieGreen

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  parent: SyndicateOperativeGearFull
  equipment:
    pocket2: AgentUplinkRadio45TC # DeltaV - allows them to buy Agent armor
    eyes: ClothingEyesHudSyndicateAgent
    outerClothing: ClothingOuterCoatCybersunWindbreaker # DeltaV - removal of armor
#    shoes: ClothingShoesBootsMagSyndie # DeltaV - removal of armor
    id: SyndiAgentPDA
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - SyndiHypo
    - SawAdvanced
    - Cautery
    - CombatKnife
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - HandheldHealthAnalyzer
    - CombatMedipen
    # - DeathAcidifierImplanter # DeltaV - more TC less acid
    - BionicVoiceMaskImplanter # DeltaV - Voice masking implant
    - OmnimedToolSyndie # Shitmed

- type: chameleonOutfit
  id: NukeopsMedicOutfit
  name: roles-antag-nuclear-operative-agent-name
  startingGear: SyndicateOperativeMedicFull
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieMedic
    neck: ClothingNeckScarfStripedLightBlue

#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    pocket2: BaseUplinkRadio65TC # DeltaV - more TC less armor
