- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  guides: [ NuclearOperatives ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 108000 # DeltaV - 30 hours
  - !type:DepartmentTimeRequirement # DeltaV - engi dept time requirement
    department: Engineering
    time: 7200 # DeltaV - 2 hours
  - !type:RoleTimeRequirement # DeltaV - salvage time requirement
    role: JobSalvageSpecialist
    time: 7200 # DeltaV - 2 hours
  - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    time: 36000 # DeltaV - 10 hours

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  guides: [ NuclearOperatives ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 108000 # DeltaV - 30 hours
  - !type:RoleTimeRequirement #Delta V - they should be able to make basic chems
    role: JobChemist
    time: 14400 # DeltaV- 4 hours

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  guides: [ NuclearOperatives ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 216000 # DeltaV - 60 hours
  - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    time: 36000 # DeltaV - 10 hours, was 5
  - !type:DepartmentTimeRequirement # DeltaV - Command dept time requirement
    department: Command
    time: 36000 # DeltaV - 10 hours
  - !type:WhitelistRequirement # DeltaV - Whitelist requirement
  # should be changed to nukie playtime when thats tracked (wyci)

- type: startingGear
  id: SyndicateOperativeGearFullNoUplink
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket2: PlushieCarp
    belt: ClothingBeltMilitaryWebbing
  storage:
    back:
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter
    - BionicVoiceMaskImplanter # Delta-V - Voice masking implant

#Nuclear Operative Gear
- type: startingGear
  id: SyndicateOperativeGearFull
  parent: SyndicateOperativeGearFullNoUplink
  equipment:
    pocket2: BaseUplinkRadio45TC # DeltaV removal of armor
    outerClothing: ClothingOuterCoatSyndieCap # DeltaV removal of armor

- type: chameleonOutfit
  id: NukeopsOutfit
  name: roles-antag-nuclear-operative-name
  startingGear: SyndicateOperativeGearFullNoUplink
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndie
    neck: ClothingNeckScarfStripedSyndieRed

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    neck: SyndicateWhistle
<<<<<<< HEAD
    pocket2: CommanderUplinkRadio45TC # DeltaV allows them to buy commander armor
    outerClothing: ClothingOuterCoatSyndieCapArmored # DeltaV removal of armor
#  inhand: # DeltaV - Removal Of War.
#  - NukeOpsDeclarationOfWar
=======
    pocket2: CommanderUplinkRadio45TC # DeltaV - allows them to buy commander armor
    outerClothing: ClothingOuterCoatSyndieCapArmored # DeltaV - removal of armor
  inhand:
  - NukeOpsDeclarationOfWar

- type: chameleonOutfit
  id: NukeopsCommanderOutfit
  name: roles-antag-nuclear-operative-commander-name
  startingGear: SyndicateCommanderGearFull
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieCommander
    neck: ClothingNeckScarfStripedSyndieGreen
>>>>>>> 496c0c511e446e3b6ce133b750e6003484d66e30

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  parent: SyndicateOperativeGearFull
  equipment:
    pocket2: AgentUplinkRadio45TC #DeltaV allows them to buy Agent armor
    eyes: ClothingEyesHudSyndicateAgent
    outerClothing: ClothingOuterCoatCybersunWindbreaker # DeltaV removal of armor
#    shoes: ClothingShoesBootsMagSyndie # DeltaV removal of armor
    id: SyndiAgentPDA
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - SyndiHypo
    - SawAdvanced
    - Cautery
    - CombatKnife
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - HandheldHealthAnalyzer
    - CombatMedipen
    - DeathAcidifierImplanter
    - BionicVoiceMaskImplanter # Delta-V - Voice masking implant
    - OmnimedToolSyndie # Shitmed

- type: chameleonOutfit
  id: NukeopsMedicOutfit
  name: roles-antag-nuclear-operative-agent-name
  startingGear: SyndicateOperativeMedicFull
  icon: "JobIconSyndicate"
  equipment:
    head: ClothingHeadHelmetHardsuitSyndieMedic
    neck: ClothingNeckScarfStripedLightBlue

#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    pocket2: BaseUplinkRadio65TC # DeltaV more TC less armor
