- type: antag
  id: HeadRev
  name: roles-antag-rev-head-name
  antagonist: true
  setPreference: true
  objective: roles-antag-rev-head-objective
  requirements:
  - !type:OverallPlaytimeRequirement # DeltaV - Playtime requirement
    time: 7200 # DeltaV - 2 hours
  - !type:DepartmentTimeRequirement # DeltaV - Command dept time requirement
    department: Command
    time: 3600 # DeltaV - 1 hours

- type: antag
  id: Rev
  name: roles-antag-rev-name
  antagonist: true
  setPreference: false
  objective: roles-antag-rev-objective
