- type: antag
  id: Thief
  name: roles-antag-thief-name
  antagonist: true
  setPreference: true
  objective: roles-antag-thief-objective
  guides: [ Thieves ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 24h # DeltaV - was 1h

- type: startingGear
  id: ThiefGear
  storage:
    back:
    #- ThiefBeacon # DeltaV - no more objectives
    - SatchelThief
    - ClothingHandsChameleonThief # DeltaV - add back thieving gloves
