- type: antag
  id: Traitor
  name: roles-antag-syndicate-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-objective
  guides: [ NuclearOperatives ]
  requirements:
  - !type:OverallPlaytimeRequirement # DeltaV - Playtime requirement
    time: 7200 # DeltaV - 2 hours

- type: antag
  id: TraitorSleeper
  name: roles-antag-syndicate-agent-sleeper-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-sleeper-objective
