- type: antag
  id: Traitor
  name: roles-antag-syndicate-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-syndicate-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement # DeltaV - Playtime requirement
    time: 86400 # DeltaV - 24 hours
