- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
        prob: 0.3
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetAltSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
##      - id: ClothingOuterCoatWarden # DeltaV - remove this coat from standard gameplay.
##      - id: ClothingOuterWinterCoatWarden # DeltaV - remove this coat from standard gameplay.
      - id: ClothingOuterStasecCoatWarden # DeltaV - replace erroneous coats with appropriate uniform.
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitCombatWarden # DeltaV - ClothingOuterHardsuitWarden replaced in favour of warden's riot combat hardsuit.
      - id: HoloprojectorSecurity
      - id: BoxPDAPrisoner # Delta-V
      - id: BoxEncryptionKeyPrisoner #Delta-V
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3
      - id: ClothingUnderSocksStripedSecurityJackboots
        prob: 0.5

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
        prob: 0.3
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetAltSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
##      - id: ClothingOuterCoatWarden # DeltaV - remove this coat from standard gameplay.
##      - id: ClothingOuterWinterCoatWarden # DeltaV - remove this coat from standard gameplay.
      - id: ClothingOuterStasecCoatWarden # DeltaV - replace erroneous coats with appropriate uniform.
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: HoloprojectorSecurity
      - id: BoxPDAPrisoner # Delta-V
      - id: BoxEncryptionKeyPrisoner #Delta-V
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3
      - id: ClothingUnderSocksStripedSecurityJackboots
        prob: 0.5

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        prob: 0.8
      - id: ClothingUniformJumpsuitSecGrey
        prob: 0.3
      - id: ClothingUniformJumpsuitSecBlue # DeltaV - consistency with other sec uniforms
        prob: 0.3
      - id: ClothingUniformJumpsuitSec # DeltaV - consistency with other sec uniforms
        prob: 0.3
      - id: ClothingUniformJumpskirtSecGrey # DeltaV - consistency with other sec uniforms
        prob: 0.3
      - id: ClothingUniformJumpskirtSecBlue # DeltaV - consistency with other sec uniforms
        prob: 0.3
      - id: ClothingUniformJumpskirtSec # DeltaV - consistency with other sec uniforms
        prob: 0.3
      - id: ClothingHeadHelmetBasic
      - id: ClothingHeadHelmetInsulated # Nyanotrasen - Insulative headgear
        prob: 0.4
      - id: ClothingOuterArmorPlateCarrier # DeltaV - ClothingOuterArmorBasic replaced in favour of plate carrier and stabproof vest
      - id: ClothingOuterArmorDuraVest # DeltaV - ClothingOuterArmorBasic replaced in favour of plate carrier and stabproof vest
      - id: ClothingOuterStasecSweater # DeltaV - in case the officers get cold :3
        prob: 0.75
      - id: ClothingUniformJumpsuitSecFormal # DeltaV - emergency parade time, Central's coming to visit
        prob: 0.15
      - id: ClothingUniformJumpskirtSecFormal # DeltaV - emergency parade time, Central's coming to visit
        prob: 0.15
      - id: ClothingBeltSecurityFilled
      - id: Flash
        prob: 0.5
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetSecurity
      - id: ClothingHandsGlovesColorBlack
      - id: ClothingShoesBootsJack
      - id: WeaponMeleeNeedle
        prob: 0.1
      - id: HoloprojectorSecurity
        prob: 0.6
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3

- type: entity
  id: LockerBrigmedicFilled
  suffix: Corpsman, Filled # DeltaV - rename brigmedic to corpsman
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
##      - id: ClothingOuterHardsuitCombatCorpsman # DeltaV - ClothingOuterHardsuitBrigmedic replaced in favour of corpsman's combat hardsuit; removing from standard filled locker to place in hardsuit filled locker.
##      - id: BoxSterileMask # DeltaV - Sterile masks have next to no use and bloat this locker.
      - id: ClothingHeadHatBeretCorpsman # DeltaV - ClothingHeadHatBeretBrigmedic replaced in favour of corpsman beret.
##      - id: ClothingOuterCoatAMG # DeltaV - Remove from standard gameplay.
      - id: ClothingOuterCoatLabCorpsman # DeltaV - replace AMG coat with more uniform option.
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
##      - id: ClothingUniformJumpskirtOfLife # DeltaV - nah
##        prob: 0.1
      - id: HandheldGPSBasic # Delta V - added it for tracking the implant tracker pop up.
      - id: MedkitFilled
      - id: MedkitCombatFilled
        prob: 0.6
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.7
##      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse # DeltaV - why
##        prob: 0.15
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3

# DeltaV - adding corpsman locker w/ hardsuit

- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Corpsman, Filled, Hardsuit
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
      - id: ClothingHeadHatBeretCorpsman
      - id: ClothingOuterCoatLabCorpsman
      - id: ClothingOuterHardsuitCombatCorpsman
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: HandheldGPSBasic # Added GPS because I just think it should be there tbh.
      - id: MedkitFilled
      - id: MedkitCombatFilled
        prob: 0.6
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.7
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3

# DeltaV - end addition

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
        prob: 0.3
##      - id: ClothingHeadHatFedoraBrown # DeltaV - Replace in favour of proper uniform.
      - id: ClothingHeadHatBeretForensicSpecialist # DeltaV - Add forensic beret.
##      - id: ClothingNeckTieDet # DeltaV - remove the outdated look. stop breaking uniform.
##      - id: ClothingOuterVestDetective # DeltaV - see above
##      - id: ClothingOuterCoatDetective # DeltaV - Replace in favour of proper uniform.
      - id: ClothingOuterStasecCoatDet # DeltaV - Add forensic coat.
      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: LogProbeCartridge
      - id: BoxForensicPad
      - id: DrinkDetFlask
      - id: ClothingHandsGlovesForensic
      - id: RubberStampDetective
      - id: HoloprojectorSecurity
      - id: BoxEvidenceMarkers
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      # NT is cheap, what can you do...
      - id: Wirecutter
        prob: 0.9
      - id: Screwdriver
        prob: 0.9
      - id: Multitool
        prob: 0.5

- type: entity
  parent: GunSafe
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: GunSafe
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: GunSafe
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunDrozd
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: GunSafe
  name: wt550 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entity
  parent: GunSafe
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponLaserCarbine
      amount: 3
