- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
#        prob: 0.3 # DeltaV - just give them the damn disabler
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
#      - id: ClothingOuterCoatWarden # DeltaV - removed for incongruence
#      - id: ClothingOuterWinterWarden # DeltaV - removed for incongruence
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: ClothingOuterHardsuitCombatWarden # DeltaV - ClothingOuterHardsuitWarden replaced in favour of warden's riot combat hardsuit.
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      # Begin DeltaV additions
      - id: BoxPDAPrisoner
      - id: BoxEncryptionKeyPrisoner
      - id: LunchboxSecurityFilledRandom
        prob: 0.3
      - id: ClothingOuterVestPlateCarrierAdv
      - id: ClothingHeadsetAltSecurity # Restored from upstream merge.
      # End DeltaV additions
      - id: ClothingNeckShockCollar
        amount: 2
      - id: RemoteSignaller
        amount: 2
      - id: ClothingShoesBootsSecurityMagboots # DeltaV - Added security magboots.

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: WeaponDisabler
#        prob: 0.3 # DeltaV - just give them the damn disabler
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsJack
#      - id: ClothingOuterCoatWarden # DeltaV - removed for incongruence
#      - id: ClothingOuterWinterWarden # DeltaV - removed for incongruence
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: HoloprojectorSecurity
      - id: BookSpaceLaw
      # Begin DeltaV additions
      - id: BoxPDAPrisoner
      - id: BoxEncryptionKeyPrisoner
      - id: LunchboxSecurityFilledRandom
        prob: 0.3
      - id: ClothingOuterVestPlateCarrierAdv
      - id: ClothingHeadsetAltSecurity # Restored from upstream merge.
      # End DeltaV additions
      - id: ClothingNeckShockCollar
        amount: 2
      - id: RemoteSignaller
        amount: 2

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        prob: 0.8
#      - id: ClothingUniformJumpsuitSecGrey # DeltaV - remove uniforms from sec lockers
#        prob: 0.3
      - id: ClothingHeadHelmetBasic
      - id: ClothingHeadHelmetInsulated # Nyanotrasen - Insulative headgear
        prob: 0.4
      - id: ClothingOuterArmorPlateCarrier # DeltaV - ClothingOuterArmorBasic replaced in favour of plate carrier and stabproof vest
      - id: ClothingOuterArmorDuraVest
      - id: ClothingBeltSecurityFilled
      - id: Flash
#        prob: 0.5 # DeltaV - standardise spare flash
      - id: ClothingEyesGlassesSecurity
      - id: ClothingHeadsetSecurity
      - id: ClothingHandsGlovesColorBlack
      - id: ClothingShoesBootsJack
      - id: WeaponMeleeNeedle
        prob: 0.1
      - id: HoloprojectorSecurity
        prob: 0.6
      - id: BookSpaceLaw
        prob: 0.5
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3

- type: entity
  id: LockerBrigmedicFilled
  suffix: Corpsman, Filled # DeltaV - rename brigmedic to corpsman
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesCorpsman
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
#      - id: ClothingOuterHardsuitCombatCorpsman # DeltaV - ClothingOuterHardsuitBrigmedic replaced in favour of corpsman's combat hardsuit; removing from standard filled locker to place in hardsuit filled locker.
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretCorpsman # DeltaV - ClothingHeadHatBeretBrigmedic replaced in favour of corpsman beret.
      - id: ClothingHeadsetBrigmedic # DeltaV - add spare headset.
#      - id: ClothingOuterCoatAMG # DeltaV - removed until I can resprite it or replace it.
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
#      - id: ClothingUniformJumpskirtOfLife # DeltaV - removed for incongruence
#        prob: 0.1
      - id: ClothingBeltCorpsmanWebbing # DeltaV - added spare webbing
      - id: HandheldGPSBasic # Delta V - added it for tracking the implant tracker pop up.
      - id: MedkitFilled
      - id: MedkitCombatFilled
        prob: 0.6
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.7
#      - id: ClothingNeckCloakMoth #bzzz Moth-pocalypse # DeltaV - removed for incongruence
#        prob: 0.15
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3

# DeltaV - adding corpsman locker w/ hardsuit

- type: entity
  id: LockerBrigmedicFilledHardsuit
  suffix: Corpsman, Filled, Hardsuit
  parent: LockerBrigmedic
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesCorpsman
      - id: WeaponDisabler
      - id: TrackingImplanter
        amount: 2
      - id: ClothingOuterHardsuitCombatCorpsman
      - id: ClothingShoesBootsSecurityMagboots # Added security magboots.
      - id: BoxSterileMask
      - id: ClothingHeadHatBeretCorpsman # Add corpsman beret.
      - id: ClothingHeadsetBrigmedic # Add spare headset.
      - id: ClothingUniformJumpsuitBrigmedic
      - id: ClothingUniformJumpskirtBrigmedic
      - id: ClothingBeltCorpsmanWebbing # Added spare webbing
      - id: HandheldGPSBasic # Added GPS because I just think it should be there tbh.
      - id: MedkitFilled
      - id: MedkitCombatFilled
        prob: 0.6
      - id: MedkitAdvancedFilled
        prob: 0.4
      - id: MedkitOxygenFilled
        prob: 0.3
      - id: MedkitBruteFilled
        prob: 0.3
      - id: MedkitToxinFilled
        prob: 0.3
      - id: MedkitBurnFilled
        prob: 0.7
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3

# DeltaV - end addition

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: StorageFill
    contents:
      - id: ClothingEyesGlassesSecurity
#        prob: 0.3 # DeltaV - standardise until HUD balance worked out
#      - id: ClothingHeadHatFedoraBrown # DeltaV - removed for incongruence
#      - id: ClothingNeckTieDet # DeltaV - removed for incongruence
#      - id: ClothingOuterVestDetective # DeltaV - removed for incongruence
#      - id: ClothingOuterCoatDetective # DeltaV - removed for incongruence
      - id: ClothingHeadsetSecurity # DeltaV - add spare headset.
      - id: FlippoEngravedLighter # DeltaV - add due to removal of trench coat
      - id: FlashlightSeclite
      - id: ForensicScanner
      - id: LogProbeCartridge
      - id: BoxForensicPad
      - id: DrinkDetFlask
      - id: ClothingHandsGlovesForensic
      - id: RubberStampDetective
      - id: HoloprojectorSecurity
      - id: BoxEvidenceMarkers
      - id: HandLabeler
      - id: BoxTapeRecorder # DeltaV
      - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
        prob: 0.3

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: StorageFill
    contents:
      - id: ClothingHeadHelmetBombSuit
      - id: ClothingOuterSuitBomb
      # NT is cheap, what can you do...
      - id: Wirecutter
        prob: 0.9
      - id: Screwdriver
        prob: 0.9
      - id: Multitool
        prob: 0.5

- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunDrozd
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: MagazineShotgun
      amount: 4

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: [GunSafeBaseSecure, BaseRestrictedContraband]
  name: wt550 safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entity
  parent: GunSafeBaseSecure
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: StorageFill
    contents:
    - id: WeaponLaserCarbine
      amount: 3
