- type: entity
  id: LockerWardenFilledHardsuit
  suffix: Filled, Hardsuit
  parent: LockerWarden
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:AllSelector
        children:
        - !type:NestedSelector
          tableId: FillLockerWarden
        - !type:NestedSelector
          tableId: FillLockerWardenHardsuit

- type: entity
  id: LockerWardenFilled
  suffix: Filled
  parent: LockerWarden
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerWarden

- type: entityTable
  id: FillLockerWarden
  table: !type:AllSelector
    children:
    - id: FlashlightSeclite
    - id: WeaponDisabler
    - id: WeaponTaser
    - id: ClothingBeltSecurityFilled
    - id: Flash
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHandsGlovesCombat
    #- id: ClothingShoesBootsJack # DeltaV - Moved to dresser
    #- id: ClothingOuterCoatWarden # DeltaV - removed for incongruence
    #- id: ClothingOuterWinterWarden # DeltaV - removed for incongruence
    - id: RubberStampWarden
    - id: DoorRemoteArmory
    - id: HoloprojectorSecurity
    #- id: BookSpaceLaw # DeltaV - Moved to dresser
    - id: ClothingBackpackElectropack
      amount: 2
    #- id: RemoteSignaller # DeltaV - Moved to dresser
    #  amount: 2
    #- id: NetworkConfigurator # DeltaV - Moved to dresser
    #- id: Binoculars # DeltaV - Moved to Dresser
    - id: WeaponEnergyShotgun
    # Begin DeltaV additions
    - id: BoxPDAPrisoner
    - id: BoxEncryptionKeyPrisoner
    - id: LunchboxSecurityFilledRandom
      prob: 0.3
    - id: ClothingOuterVestPlateCarrierAdv
    - id: ClothingHeadsetAltSecurity # Restored from upstream merge.
    #- id: ClothingNeckShockCollar # DeltaV - Moved to dresser I guess?
    #  amount: 2
    # End DeltaV additions

- type: entityTable
  id: FillLockerWardenHardsuit
  table: !type:AllSelector
    children:
    - id: ClothingOuterHardsuitCombatWarden # DeltaV - ClothingOuterHardsuitWarden replaced in favour of warden's riot combat hardsuit.
    - id: ClothingShoesBootsSecurityMagboots # DeltaV - Added security magboots.
    - id: OxygenTankFilled
    - id: NitrogenTankFilled
    - id: ClothingMaskBreath

- type: entity
  id: LockerSecurityFilled
  suffix: Filled
  parent: LockerSecurity
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerSecurity

- type: entityTable
  id: FillLockerSecurity
  table: !type:AllSelector
    children:
    - id: FlashlightSeclite
      prob: 0.8
    - id: WeaponDisabler
    - id: WeaponTaser
    #- id: ClothingUniformJumpsuitSecGrey # DeltaV - remove uniforms from sec lockers
    #  prob: 0.3
    - id: ClothingHeadHelmetBasic
    #- id: ClothingOuterArmorBasic # DeltaV - ClothingOuterArmorBasic replaced in favour of plate carrier and stabproof vest
    - id: ClothingBeltSecurityFilled
    - id: Flash
    #  prob: 0.5 # DeltaV - standardise spare flash
    - id: ClothingEyesGlassesSecurity
    - id: ClothingHeadsetSecurity
    - id: ClothingHandsGlovesColorBlack
    - id: ClothingShoesBootsJack
    - id: WeaponMeleeNeedle
      prob: 0.1
    - id: HoloprojectorSecurity
      prob: 0.6
    - id: BookSpaceLaw
      prob: 0.5
    - id: ClothingHeadHelmetInsulated # Nyanotrasen - Insulative headgear
      prob: 0.4
    - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
      prob: 0.3
    - id: ClothingOuterArmorPlateCarrier # DeltaV - ClothingOuterArmorBasic replaced in favour of plate carrier and stabproof vest
    - id: ClothingOuterArmorDuraVest # DeltaV

- type: entity
  id: LockerBrigmedicFilled
  suffix: Corpsman, Filled # DeltaV - rename brigmedic to corpsman
  parent: LockerBrigmedic
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerBrigmedic

- type: entityTable
  id: FillLockerBrigmedic
  table: !type:AllSelector
    children:
    - id: WeaponTaser
    - id: ClothingEyesGlassesCorpsman
    - id: WeaponDisabler
    - id: TrackingImplanter
      amount: 2
    #- id: ClothingOuterHardsuitCombatCorpsman # DeltaV - ClothingOuterHardsuitBrigmedic replaced in favour of corpsman's combat hardsuit; removing from standard filled locker to place in hardsuit filled locker.
    - id: BoxSterileMask
    # - id: ClothingHeadHatBeretCorpsman # DeltaV - ClothingHeadHatBeretBrigmedic replaced in favour of corpsman beret. # DeltaV - added corpsman uniform to secdrobe
    - id: ClothingHeadsetBrigmedic # DeltaV - add spare headset.
#   - id: ClothingOuterCoatAMG # DeltaV - removed until I can resprite it or replace it.
    # - id: ClothingUniformJumpsuitBrigmedic # DeltaV - added corpsman uniform to secdrobe
    # - id: ClothingUniformJumpskirtBrigmedic # DeltaV - added corpsman uniform to secdrobe
    #- id: ClothingUniformJumpskirtOfLife # DeltaV - removed for incongruence
    #  prob: 0.1
    # Begin DeltaV additions
    - id: ClothingBeltCorpsmanWebbing # DeltaV - added spare webbing
    - id: HandheldGPSBasic # Delta V - added it for tracking the implant tracker pop up.
    - id: BoxBodyBag
    - id: EmergencyRollerBedSpawnFolded
    - id: MedkitCombatFilled
    - id: Portafib
    # End DeltaV additions
    - id: MedkitFilled
    - !type:GroupSelector
      prob: 0.7
      children:
      - id: MedkitCombatFilled
        weight: 1.6
      - id: MedkitAdvancedFilled
      - id: MedkitOxygenFilled
        weight: 0.8
      - id: MedkitBruteFilled
        weight: 0.8
      - id: MedkitToxinFilled
        weight: 0.8
      - id: MedkitBurnFilled
        weight: 1.8
    #- id: ClothingNeckCloakMoth #bzzz Moth-pocalypse # DeltaV - removed for incongruence
    #  prob: 0.15
    - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
      prob: 0.3

# DeltaV - adding corpsman locker w/ hardsuit
- type: entityTable
  id: FillLockerBrigmedicHarduit
  table: !type:AllSelector
    children:
    - id: ClothingOuterHardsuitCombatCorpsman # DeltaV - ClothingOuterHardsuitWarden replaced in favour of warden's riot combat hardsuit.
    - id: ClothingShoesBootsSecurityMagboots # DeltaV - Added security magboots.
    - id: OxygenTankFilled
    - id: NitrogenTankFilled
    - id: ClothingMaskBreath
# END DeltaV - adding corpsman locker w/ hardsuit

- type: entity
  id: LockerDetectiveFilled
  suffix: Filled
  parent: LockerDetective
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillLockerDetective

- type: entityTable
  id: FillLockerDetective
  table: !type:AllSelector
    children:
    - id: ClothingEyesGlassesNoir
    # Begin DeltaV Removals - removed for incongruence
    #- id: ClothingHeadHatDetGadget
    #- id: ClothingNeckTieDet
    #- id: ClothingOuterVestDetective
    #- id: ClothingOuterCoatDetectiveLoadout
    # End DeltaV Removals
    - id: ClothingHeadsetSecurity # DeltaV - add spare headset.
    - id: FlippoEngravedLighter
    - id: FlashlightSeclite
    - id: ForensicScanner
    - id: LogProbeCartridge
    - id: BoxForensicPad
    - id: DrinkDetFlask
    - id: ClothingHandsGlovesForensic
    - id: RubberStampDetective
    - id: HoloprojectorSecurity
    - id: BoxEvidenceMarkers
    - id: HandLabeler
    - id: BoxTapeRecorder # DeltaV
    - id: LunchboxSecurityFilledRandom # Delta-v Lunchboxes!
      prob: 0.3

- type: entity
  id: ClosetBombFilled
  parent: ClosetBomb
  suffix: Filled
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillClosetBomb

- type: entityTable
  id: FillClosetBomb
  table: !type:AllSelector
    children:
    - id: ClothingHeadHelmetBombSuit
    - id: ClothingOuterSuitBomb
    - id: Wirecutter
    - id: Screwdriver
    - id: Multitool
      prob: 0.5

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeDisabler
  name: disabler safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeDisabler

- type: entityTable
  id: FillGunSafeDisabler
  table: !type:AllSelector
    children:
    - id: WeaponDisabler
      amount: 5

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafePistolMk58
  name: mk58 safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafePistolMk58

- type: entityTable
  id: FillGunSafePistolMk58
  table: !type:AllSelector
    children:
    - id: WeaponPistolMk58
      amount: 4
    - id: MagazinePistol
      amount: 8

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeRifleLecter
  name: lecter safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeRifleLecter

- type: entityTable
  id: FillGunSafeRifleLecter
  table: !type:AllSelector
    children:
    - id: WeaponRifleLecter
      amount: 2
    - id: MagazineRifle
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeSubMachineGunDrozd
  name: drozd safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeSubMachineGunDrozd

- type: entityTable
  id: FillGunSafeSubMachineGunDrozd
  table: !type:AllSelector
    children:
    - id: WeaponSubMachineGunDrozd
      amount: 2
    - id: MagazinePistolSubMachineGun
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeShotgunEnforcer
  name: enforcer safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunEnforcer

- type: entityTable
  id: FillGunSafeShotgunEnforcer
  table: !type:AllSelector
    children:
    - id: WeaponShotgunEnforcer
      amount: 2
    - id: BoxLethalshot
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeShotgunKammerer
  name: kammerer safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeShotgunKammerer

- type: entityTable
  id: FillGunSafeShotgunKammerer
  table: !type:AllSelector
    children:
    - id: WeaponShotgunKammerer
      amount: 2
    - id: BoxLethalshot
      amount: 4

- type: entity
  id: GunSafeSubMachineGunWt550
  suffix: Wt550
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  name: wt550 safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeSubMachineGunWt550

- type: entityTable
  id: FillGunSafeSubMachineGunWt550
  table: !type:AllSelector
    children:
    - id: WeaponSubMachineGunWt550
      amount: 2
    - id: MagazinePistolSubMachineGunTopMounted
      amount: 4

- type: entity
  parent: [GunSafeBaseSecure, BaseSecurityContraband]
  id: GunSafeLaserCarbine
  name: laser safe
  components:
  - type: EntityTableContainerFill
    containers:
      entity_storage: !type:NestedSelector
        tableId: FillGunSafeLaserCarbine

- type: entityTable
  id: FillGunSafeLaserCarbine
  table: !type:AllSelector
    children:
    - id: WeaponLaserCarbine
      amount: 3
