- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
      department: Security
      time: 7200 # 2 hours
  startingGear: CorpsmanGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  - External
  - Corpsman
  extendedAccess:
  - Chemistry
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: CorpsmanGear # see Prototypes/Roles/Jobs/Fun/misc_startinggear.yml for "BrigmedicGear"
  equipment:
    id: BrigmedicPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltMedicalEMTFilled
    pocket1: WeaponPistolMk58Nonlethal
  storage:
    back:
    - EmergencyRollerBedSpawnFolded
    - BodyBagFolded
    - Portafib
    - BruteAutoInjector
    - BruteAutoInjector
    - BurnAutoInjector
    - BurnAutoInjector
    - MagazinePistol
