- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 21600 # 6 hrs
    - !type:RoleTimeRequirement # DeltaV - JobSecurityOfficer time requirement
      role: JobSecurityOfficer
      time: 21600 # DeltaV - 6 hrs
  startingGear: CorpsmanGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  - External
  - Corpsman
  extendedAccess:
  - Chemistry
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: CorpsmanGear # see Prototypes/Roles/Jobs/Fun/misc_startinggear.yml for "BrigmedicGear"
  equipment:
    eyes: ClothingEyesHudMedical
    id: CorpsmanPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltCorpsmanWebbingFilled
    pocket1: WeaponPistolMk58Nonlethal
  storage:
    back:
    - EmergencyRollerBedSpawnFolded
    - BodyBagFolded
    - Portafib
    - BruteAutoInjector
    - BruteAutoInjector
    - BurnAutoInjector
    - BurnAutoInjector
    - MagazinePistol
