- type: job
  id: ForensicMantis
  name: job-name-mantis
  description: job-description-mantis
  playTimeTracker: JobForensicMantis
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000
    - !type:DepartmentTimeRequirement
      department: Epistemics # DeltaV - Epistemics Department replacing Science
      time: 3600
  startingGear: ForensicMantisGear
  icon: "JobIconForensicMantis"
  supervisors: job-supervisors-rd
  antagAdvantage: 2 # DeltaV - Psionics, Has an objective item
  canBeAntag: true # DeltaV - Mantis is no longer a Detective
  access:
  - Research
  - Maintenance
  - Mantis # DeltaV - Psionic Mantis, see Resources/Prototypes/_DV/Access/epistemics.yml
  special:
  - !type:AddComponentSpecial
    components:
    - type: Psionic
    - type: MetapsionicPower

- type: startingGear
  id: ForensicMantisGear
  equipment:
    id: PsionicMantisPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetScience # DeltaV - Mantis is part of Epistemics
    belt: ClothingBeltMantis
  storage:
    back:
    - HandLabeler
    - PillMindbreakerToxin
    - BoxFolderGrey
    - RubberStampMantis

- type: chameleonOutfit
  id: ForensicMantisChameleonOutfit
  job: ForensicMantis
  equipment:
    id: PsionicMantisPDA
    eyes: ClothingEyesGlassesSunglasses
    ears: ClothingHeadsetScience
    belt: ClothingBeltMantis
    head: ClothingHeadHatFezMantis
    jumpsuit: ClothingUniformJumpsuitMantis
    outerClothing: ClothingOuterCoatMantis
    shoes: ClothingShoesBootsMantis
    gloves: ClothingHandsGlovesColorWhite
