- type: latheRecipe
  id: ClothingHeadCage
  result: ClothingHeadCage
  completetime: 4
  materials:
    Steel: 400
    Bluespace: 20

- type: latheRecipe
  id: ClothingHeadHelmetInsulated
  result: ClothingHeadHelmetInsulated
  completetime: 4
  materials:
    Steel: 400
    Bluespace: 20

- type: latheRecipe
  id: ClothingNeckShockCollar
  result: ClothingNeckShockCollar
  completetime: 2
  materials:
    Steel: 300
    Glass: 100
    Plastic: 100

- type: latheRecipe
  id: BoxShellSoulbreaker
  result: BoxShellSoulbreaker
  category: Ammo
  completetime: 4
  materials:
    Plastic: 300
    Steel: 200
    Bluespace: 200
    Glass: 100
