- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobMedicalBorg

- type: playTimeTracker
  id: JobChiefJustice

- type: playTimeTracker
  id: JobClerk

- type: playTimeTracker
  id: JobProsecutor
