
#Misc outfit startingGear definitions.

# Laika sec glasses

- type: startingGear
  id: MobSecDogLaikaGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: SecDogIDCard

#Oldstation Roles

- type: startingGear
  id: OldstationMedic
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    neck: ClothingNeckStethoscope
    shoes: ClothingShoesColorWhite
    id: MedicalIDCard
    pocket1: Brutepack
    pocket2: GlowstickBase
    belt: ClothingBeltMedical


- type: startingGear
  id: OldstationGuard
  equipment:
    jumpsuit: ClothingUniformJumpsuitSec
    shoes: ClothingShoesBootsJack
    id: SecurityIDCard
    pocket1: Flash
    pocket2: GlowstickBase

- type: startingGear
  id: OldstationEngi
  equipment:
    jumpsuit: ClothingUniformJumpsuitEngineering
    shoes: ClothingShoesBootsWork
    id: EngineeringIDCard
    mask: ClothingMaskBreath
    gloves: ClothingHandsGlovesColorYellowBudget
    pocket1: EmergencyOxygenTankFilled
    pocket2: GlowstickBase
    belt: ClothingBeltUtility

- type: startingGear
  id: OldstationScientist
  equipment:
    jumpsuit: ClothingUniformJumpsuitScientist
    shoes: ClothingShoesColorWhite
    id: ResearchIDCard
    pocket1: Pen
    pocket2: GlowstickBase

#Syndicate Pirate Radio Listener
- type: startingGear
  id: SyndicateListenerGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPyjamaSyndicateBlack
    head: ClothingHeadPyjamaSyndicateBlack
    ears: ClothingHeadsetAltSyndicateListening
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesSlippers
    id: SyndiPDA
  innerClothingSkirt: ClothingUniformJumpsuitPyjamaSyndicatePink
  
# Syndicate Paramedic

- type: startingGear
  id: SyndicateParamedicGear
  equipment:
    jumpsuit: UniformColourScrubsCybersun
    back: ClothingBackpackDuffelSyndicateFilledMedical
    shoes: ClothingShoesChameleonNoSlips
    eyes: ClothingEyesHudSyndicateMedical
    head: ClothingHeadHatSurgcapCybersun
    outerClothing: CybersunWindbreaker
    id: SyndiPDA
    belt: ClothingBeltParamedicFilled
    pocket1: HandheldGPSBasic # DeltaV - Give Paramedics useful tools on spawn
    pocket2: HandheldCrewMonitor # DeltaV - Give Paramedics useful tools on spawn
    mask: ClothingMaskSterile
    belt: ClothingBeltMedicalFilled