name: "Labels: Review"

on:
  pull_request_target:
    types: [review_requested]
  pull_request_review:
    types: [submitted]

permissions:
  pull-requests: write
  issues: write
  contents: write

jobs:
  add_label:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target'
    steps:
    - uses: actions-ecosystem/action-add-labels@v1
      with:
        labels: "S: Needs Review"
    - uses: actions-ecosystem/action-remove-labels@v1
      with:
        labels: "S: Awaiting Changes"

  # Doesn't work on prs from foreign repos currently
  #handle_review:
  #  runs-on: ubuntu-latest
  #  if: github.event_name == 'pull_request_review'
  #  steps:
  #  - uses: actions-ecosystem/action-add-labels@v1
  #    if: |
  #      github.event.review.state == 'changes_requested' &&
  #      (github.event.review.author_association == 'OWNER' ||
  #       github.event.review.author_association == 'MEMBER')
  #    with:
  #      labels: "S: Awaiting Changes"
  #
  #  - uses: actions-ecosystem/action-remove-labels@v1
  #    if: |
  #      github.event.review.state == 'changes_requested' &&
  #      (github.event.review.author_association == 'OWNER' ||
  #       github.event.review.author_association == 'MEMBER')
  #    with:
  #      labels: "S: Needs Review"
