- type: antag
  id: Conspirator
  name: roles-antag-conspirator-name
  antagonist: true
  setPreference: true
  objective: roles-antag-conspirator-objective
  guides: [ Conspirators ]
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 86400 # DeltaV - 24h
